/**
 * ProcedureDx Universal Supply Closet
 * Complete inventory of medical supplies - learners must choose from this full list
 * Simulates walking into a real supply room
 */

const SUPPLY_CLOSET = [
    // PPE
    { id: 'gloves-nonsterile-s', name: 'Non-sterile gloves (Small)', icon: '🧤', category: 'PPE' },
    { id: 'gloves-nonsterile-m', name: 'Non-sterile gloves (Medium)', icon: '🧤', category: 'PPE' },
    { id: 'gloves-nonsterile-l', name: 'Non-sterile gloves (Large)', icon: '🧤', category: 'PPE' },
    { id: 'gloves-sterile-6', name: 'Sterile gloves (Size 6)', icon: '🧤', category: 'PPE' },
    { id: 'gloves-sterile-65', name: 'Sterile gloves (Size 6.5)', icon: '🧤', category: 'PPE' },
    { id: 'gloves-sterile-7', name: 'Sterile gloves (Size 7)', icon: '🧤', category: 'PPE' },
    { id: 'gloves-sterile-75', name: 'Sterile gloves (Size 7.5)', icon: '🧤', category: 'PPE' },
    { id: 'gloves-sterile-8', name: 'Sterile gloves (Size 8)', icon: '🧤', category: 'PPE' },
    { id: 'surgical-mask', name: 'Surgical mask', icon: '😷', category: 'PPE' },
    { id: 'n95-respirator', name: 'N95 respirator', icon: '😷', category: 'PPE' },
    { id: 'face-shield', name: 'Face shield', icon: '🛡️', category: 'PPE' },
    { id: 'surgical-cap', name: 'Surgical cap/bouffant', icon: '🎓', category: 'PPE' },
    { id: 'sterile-gown', name: 'Sterile surgical gown', icon: '🥼', category: 'PPE' },
    { id: 'isolation-gown', name: 'Isolation gown (non-sterile)', icon: '🥼', category: 'PPE' },
    { id: 'shoe-covers', name: 'Shoe covers', icon: '👟', category: 'PPE' },
    { id: 'lead-apron', name: 'Lead apron', icon: '🦺', category: 'PPE' },
    { id: 'thyroid-shield', name: 'Thyroid shield', icon: '🛡️', category: 'PPE' },
    { id: 'safety-glasses', name: 'Safety glasses', icon: '👓', category: 'PPE' },
    { id: 'goggles', name: 'Protective goggles', icon: '🥽', category: 'PPE' },
    // Antiseptics
    { id: 'chlorhexidine-swab', name: 'Chlorhexidine swab stick (2%)', icon: '🧴', category: 'Antiseptics' },
    { id: 'chlorhexidine-solution', name: 'Chlorhexidine solution (4%)', icon: '🧴', category: 'Antiseptics' },
    { id: 'betadine-swab', name: 'Betadine swab stick', icon: '🧴', category: 'Antiseptics' },
    { id: 'betadine-solution', name: 'Betadine solution (pour)', icon: '🧴', category: 'Antiseptics' },
    { id: 'alcohol-prep-pad', name: 'Alcohol prep pads (70%)', icon: '🧴', category: 'Antiseptics' },
    { id: 'hydrogen-peroxide', name: 'Hydrogen peroxide 3%', icon: '🧴', category: 'Antiseptics' },
    { id: 'benzoin-tincture', name: 'Tincture of benzoin', icon: '🧴', category: 'Antiseptics' },
    // Drapes
    { id: 'sterile-towels', name: 'Sterile towels (pack)', icon: '📄', category: 'Drapes' },
    { id: 'fenestrated-drape', name: 'Fenestrated drape', icon: '📄', category: 'Drapes' },
    { id: 'full-body-drape', name: 'Full body sterile drape', icon: '📄', category: 'Drapes' },
    { id: 'half-drape', name: 'Half drape', icon: '📄', category: 'Drapes' },
    { id: 'us-probe-cover', name: 'Sterile ultrasound probe cover', icon: '📷', category: 'Drapes' },
    { id: 'sterile-us-gel', name: 'Sterile ultrasound gel', icon: '🧴', category: 'Drapes' },
    { id: 'nonsterile-us-gel', name: 'Non-sterile ultrasound gel', icon: '🧴', category: 'Drapes' },
    { id: 'sterile-saline-pour', name: 'Sterile saline (pour bottle)', icon: '💧', category: 'Drapes' },
    { id: 'sterile-water-pour', name: 'Sterile water (pour bottle)', icon: '💧', category: 'Drapes' },
    // Anesthetics
    { id: 'lidocaine-1', name: 'Lidocaine 1% (plain)', icon: '💉', category: 'Anesthetics' },
    { id: 'lidocaine-1-epi', name: 'Lidocaine 1% with epinephrine', icon: '💉', category: 'Anesthetics' },
    { id: 'lidocaine-2', name: 'Lidocaine 2% (plain)', icon: '💉', category: 'Anesthetics' },
    { id: 'bupivacaine-05', name: 'Bupivacaine 0.5%', icon: '💉', category: 'Anesthetics' },
    { id: 'lidocaine-jelly', name: 'Lidocaine jelly 2%', icon: '🧴', category: 'Anesthetics' },
    { id: 'lidocaine-spray', name: 'Lidocaine spray (topical)', icon: '💨', category: 'Anesthetics' },
    { id: 'emla-cream', name: 'EMLA cream', icon: '🧴', category: 'Anesthetics' },
    // Syringes
    { id: 'syringe-1ml', name: 'Syringe 1mL', icon: '💉', category: 'Syringes' },
    { id: 'syringe-3ml', name: 'Syringe 3mL', icon: '💉', category: 'Syringes' },
    { id: 'syringe-5ml', name: 'Syringe 5mL', icon: '💉', category: 'Syringes' },
    { id: 'syringe-10ml', name: 'Syringe 10mL', icon: '💉', category: 'Syringes' },
    { id: 'syringe-20ml', name: 'Syringe 20mL', icon: '💉', category: 'Syringes' },
    { id: 'syringe-60ml', name: 'Syringe 60mL', icon: '💉', category: 'Syringes' },
    { id: 'syringe-60ml-catheter', name: 'Syringe 60mL catheter-tip', icon: '💉', category: 'Syringes' },
    // Needles
    { id: 'needle-18g', name: 'Needle 18g (pink)', icon: '📌', category: 'Needles' },
    { id: 'needle-20g', name: 'Needle 20g (yellow)', icon: '📌', category: 'Needles' },
    { id: 'needle-21g', name: 'Needle 21g (green)', icon: '📌', category: 'Needles' },
    { id: 'needle-22g', name: 'Needle 22g (black)', icon: '📌', category: 'Needles' },
    { id: 'needle-25g', name: 'Needle 25g (orange)', icon: '📌', category: 'Needles' },
    { id: 'needle-27g', name: 'Needle 27g (gray)', icon: '📌', category: 'Needles' },
    { id: 'needle-spinal-22g', name: 'Spinal needle 22g', icon: '📌', category: 'Needles' },
    { id: 'needle-spinal-25g', name: 'Spinal needle 25g (pencil-point)', icon: '📌', category: 'Needles' },
    { id: 'needle-introducer', name: 'Introducer needle 18g', icon: '📌', category: 'Needles' },
    { id: 'needle-butterfly-21g', name: 'Butterfly needle 21g', icon: '🦋', category: 'Needles' },
    { id: 'needle-butterfly-23g', name: 'Butterfly needle 23g', icon: '🦋', category: 'Needles' },
    // IV Supplies
    { id: 'iv-catheter-14g', name: 'IV catheter 14g', icon: '🔌', category: 'IV Supplies' },
    { id: 'iv-catheter-16g', name: 'IV catheter 16g', icon: '🔌', category: 'IV Supplies' },
    { id: 'iv-catheter-18g', name: 'IV catheter 18g', icon: '🔌', category: 'IV Supplies' },
    { id: 'iv-catheter-20g', name: 'IV catheter 20g', icon: '🔌', category: 'IV Supplies' },
    { id: 'iv-catheter-22g', name: 'IV catheter 22g', icon: '🔌', category: 'IV Supplies' },
    { id: 'iv-catheter-24g', name: 'IV catheter 24g', icon: '🔌', category: 'IV Supplies' },
    { id: 'iv-extension-set', name: 'IV extension tubing', icon: '🔌', category: 'IV Supplies' },
    { id: 'tourniquet', name: 'Tourniquet', icon: '🔗', category: 'IV Supplies' },
    { id: 'saline-flush-10ml', name: 'Saline flush 10mL', icon: '💧', category: 'IV Supplies' },
    { id: 'heparin-flush', name: 'Heparin flush', icon: '💧', category: 'IV Supplies' },
    { id: 'stopcock-3way', name: '3-way stopcock', icon: '🔌', category: 'IV Supplies' },
    { id: 't-connector', name: 'T-connector', icon: '🔌', category: 'IV Supplies' },
    // Central Lines
    { id: 'cvl-kit-triple', name: 'Central line kit (triple lumen)', icon: '📦', category: 'Central Lines' },
    { id: 'cvl-kit-double', name: 'Central line kit (double lumen)', icon: '📦', category: 'Central Lines' },
    { id: 'guidewire-j', name: 'Guidewire (J-tip)', icon: '〰️', category: 'Central Lines' },
    { id: 'dilator-cvl', name: 'Dilator (central line)', icon: '🔧', category: 'Central Lines' },
    { id: 'introducer-sheath', name: 'Introducer sheath (Cordis)', icon: '🔌', category: 'Central Lines' },
    { id: 'picc-kit', name: 'PICC line kit', icon: '📦', category: 'Central Lines' },
    // Arterial Lines
    { id: 'arterial-line-kit', name: 'Arterial line kit', icon: '📦', category: 'Arterial Lines' },
    { id: 'arterial-catheter-20g', name: 'Arterial catheter 20g', icon: '🔌', category: 'Arterial Lines' },
    { id: 'transducer-kit', name: 'Pressure transducer kit', icon: '📊', category: 'Arterial Lines' },
    { id: 'pressure-bag', name: 'Pressure bag', icon: '💨', category: 'Arterial Lines' },
    { id: 'arm-board', name: 'Arm board', icon: '📋', category: 'Arterial Lines' },
    // Airway
    { id: 'ett-60', name: 'ETT 6.0', icon: '🔌', category: 'Airway' },
    { id: 'ett-70', name: 'ETT 7.0', icon: '🔌', category: 'Airway' },
    { id: 'ett-75', name: 'ETT 7.5', icon: '🔌', category: 'Airway' },
    { id: 'ett-80', name: 'ETT 8.0', icon: '🔌', category: 'Airway' },
    { id: 'laryngoscope-mac-3', name: 'Laryngoscope Mac 3', icon: '🔦', category: 'Airway' },
    { id: 'laryngoscope-mac-4', name: 'Laryngoscope Mac 4', icon: '🔦', category: 'Airway' },
    { id: 'laryngoscope-miller', name: 'Laryngoscope Miller', icon: '🔦', category: 'Airway' },
    { id: 'video-laryngoscope', name: 'Video laryngoscope', icon: '📹', category: 'Airway' },
    { id: 'stylet', name: 'ETT stylet', icon: '〰️', category: 'Airway' },
    { id: 'bougie', name: 'Bougie', icon: '〰️', category: 'Airway' },
    { id: 'lma-4', name: 'LMA size 4', icon: '🔌', category: 'Airway' },
    { id: 'oral-airway-90', name: 'Oral airway 90mm', icon: '🦷', category: 'Airway' },
    { id: 'nasal-airway-28', name: 'Nasal airway 28Fr', icon: '👃', category: 'Airway' },
    { id: 'bvm', name: 'Bag-valve-mask', icon: '🎈', category: 'Airway' },
    { id: 'etco2-detector', name: 'ETCO2 detector', icon: '📊', category: 'Airway' },
    { id: 'cric-kit', name: 'Cricothyrotomy kit', icon: '📦', category: 'Airway' },
    { id: 'trach-tube-6', name: 'Tracheostomy tube 6.0', icon: '🔌', category: 'Airway' },
    // Suction
    { id: 'suction-yankauer', name: 'Yankauer suction', icon: '💨', category: 'Suction' },
    { id: 'suction-catheter-14', name: 'Suction catheter 14Fr', icon: '💨', category: 'Suction' },
    { id: 'suction-tubing', name: 'Suction tubing', icon: '💨', category: 'Suction' },
    // Chest Tubes
    { id: 'chest-tube-28', name: 'Chest tube 28Fr', icon: '🔌', category: 'Chest Tubes' },
    { id: 'chest-tube-32', name: 'Chest tube 32Fr', icon: '🔌', category: 'Chest Tubes' },
    { id: 'chest-tube-36', name: 'Chest tube 36Fr', icon: '🔌', category: 'Chest Tubes' },
    { id: 'pigtail-catheter', name: 'Pigtail catheter 14Fr', icon: '🔌', category: 'Chest Tubes' },
    { id: 'chest-seal-system', name: 'Chest drainage system', icon: '📦', category: 'Chest Tubes' },
    { id: 'kelly-clamp', name: 'Kelly clamp', icon: '🔧', category: 'Chest Tubes' },
    { id: 'petrolatum-gauze', name: 'Petrolatum gauze', icon: '🩹', category: 'Chest Tubes' },
    // Urinary
    { id: 'foley-kit', name: 'Foley catheter kit', icon: '📦', category: 'Urinary' },
    { id: 'foley-14fr', name: 'Foley catheter 14Fr', icon: '🔌', category: 'Urinary' },
    { id: 'foley-16fr', name: 'Foley catheter 16Fr', icon: '🔌', category: 'Urinary' },
    { id: 'foley-18fr', name: 'Foley catheter 18Fr', icon: '🔌', category: 'Urinary' },
    { id: 'coude-catheter', name: 'Coudé catheter', icon: '🔌', category: 'Urinary' },
    { id: 'straight-cath', name: 'Straight catheter', icon: '🔌', category: 'Urinary' },
    { id: 'urine-drainage-bag', name: 'Urine drainage bag', icon: '💧', category: 'Urinary' },
    { id: 'lubricant-sterile', name: 'Sterile lubricant', icon: '🧴', category: 'Urinary' },
    { id: 'lubricant-nonsterile', name: 'Water-soluble lubricant', icon: '🧴', category: 'Urinary' },
    // GI Tubes
    { id: 'ng-tube-14', name: 'NG tube 14Fr', icon: '🔌', category: 'GI Tubes' },
    { id: 'ng-tube-16', name: 'NG tube 16Fr', icon: '🔌', category: 'GI Tubes' },
    { id: 'ng-tube-18', name: 'NG tube 18Fr', icon: '🔌', category: 'GI Tubes' },
    { id: 'dobhoff-tube', name: 'Dobhoff tube', icon: '🔌', category: 'GI Tubes' },
    { id: 'stethoscope', name: 'Stethoscope', icon: '🩺', category: 'GI Tubes' },
    { id: 'cup-water-straw', name: 'Cup of water with straw', icon: '🥤', category: 'GI Tubes' },
    { id: 'emesis-basin', name: 'Emesis basin', icon: '🥣', category: 'GI Tubes' },
    // Wound Care
    { id: 'gauze-2x2', name: 'Gauze 2x2', icon: '🩹', category: 'Wound Care' },
    { id: 'gauze-4x4', name: 'Gauze 4x4', icon: '🩹', category: 'Wound Care' },
    { id: 'gauze-roll', name: 'Gauze roll (Kerlix)', icon: '🩹', category: 'Wound Care' },
    { id: 'abdominal-pad', name: 'ABD pad', icon: '🩹', category: 'Wound Care' },
    { id: 'tegaderm-small', name: 'Tegaderm (small)', icon: '🩹', category: 'Wound Care' },
    { id: 'tegaderm-large', name: 'Tegaderm (large)', icon: '🩹', category: 'Wound Care' },
    { id: 'tegaderm-chg', name: 'Tegaderm CHG dressing', icon: '🩹', category: 'Wound Care' },
    { id: 'bandaid', name: 'Adhesive bandage', icon: '🩹', category: 'Wound Care' },
    { id: 'tape-paper', name: 'Paper tape', icon: '🩹', category: 'Wound Care' },
    { id: 'tape-silk', name: 'Silk tape', icon: '🩹', category: 'Wound Care' },
    { id: 'tape-cloth', name: 'Cloth tape', icon: '🩹', category: 'Wound Care' },
    { id: 'coban', name: 'Coban wrap', icon: '🩹', category: 'Wound Care' },
    { id: 'ace-wrap', name: 'ACE wrap', icon: '🩹', category: 'Wound Care' },
    { id: 'steri-strips', name: 'Steri-strips', icon: '🩹', category: 'Wound Care' },
    { id: 'dermabond', name: 'Dermabond (skin glue)', icon: '🩹', category: 'Wound Care' },
    { id: 'stapler-skin', name: 'Skin stapler', icon: '📎', category: 'Wound Care' },
    // Sutures
    { id: 'suture-silk-2-0', name: 'Silk suture 2-0', icon: '🧵', category: 'Sutures' },
    { id: 'suture-silk-3-0', name: 'Silk suture 3-0', icon: '🧵', category: 'Sutures' },
    { id: 'suture-nylon-3-0', name: 'Nylon suture 3-0', icon: '🧵', category: 'Sutures' },
    { id: 'suture-nylon-4-0', name: 'Nylon suture 4-0', icon: '🧵', category: 'Sutures' },
    { id: 'suture-nylon-5-0', name: 'Nylon suture 5-0', icon: '🧵', category: 'Sutures' },
    { id: 'suture-vicryl-3-0', name: 'Vicryl suture 3-0', icon: '🧵', category: 'Sutures' },
    { id: 'suture-chromic-3-0', name: 'Chromic gut suture 3-0', icon: '🧵', category: 'Sutures' },
    { id: 'needle-driver', name: 'Needle driver', icon: '🔧', category: 'Sutures' },
    { id: 'forceps-adson', name: 'Adson forceps', icon: '🔧', category: 'Sutures' },
    { id: 'scissors-suture', name: 'Suture scissors', icon: '✂️', category: 'Sutures' },
    // Scalpels
    { id: 'scalpel-10', name: 'Scalpel #10 blade', icon: '🔪', category: 'Scalpels' },
    { id: 'scalpel-11', name: 'Scalpel #11 blade', icon: '🔪', category: 'Scalpels' },
    { id: 'scalpel-15', name: 'Scalpel #15 blade', icon: '🔪', category: 'Scalpels' },
    // LP Supplies
    { id: 'lp-kit', name: 'Lumbar puncture kit', icon: '📦', category: 'LP Supplies' },
    { id: 'csf-tubes', name: 'CSF collection tubes (4)', icon: '🧪', category: 'LP Supplies' },
    { id: 'manometer', name: 'CSF manometer with stopcock', icon: '📏', category: 'LP Supplies' },
    // Drainage
    { id: 'thoracentesis-kit', name: 'Thoracentesis kit', icon: '📦', category: 'Drainage' },
    { id: 'paracentesis-kit', name: 'Paracentesis kit', icon: '📦', category: 'Drainage' },
    { id: 'vacuum-bottle', name: 'Vacuum bottle (1L)', icon: '🍾', category: 'Drainage' },
    { id: 'drainage-bag', name: 'Drainage bag', icon: '💧', category: 'Drainage' },
    // Blood Draw
    { id: 'vacutainer-holder', name: 'Vacutainer holder', icon: '🔧', category: 'Blood Draw' },
    { id: 'tube-red', name: 'Red top tube', icon: '🧪', category: 'Blood Draw' },
    { id: 'tube-gold', name: 'Gold/SST tube', icon: '🧪', category: 'Blood Draw' },
    { id: 'tube-green', name: 'Green top tube (heparin)', icon: '🧪', category: 'Blood Draw' },
    { id: 'tube-lavender', name: 'Lavender tube (EDTA)', icon: '🧪', category: 'Blood Draw' },
    { id: 'tube-blue', name: 'Blue top tube (citrate)', icon: '🧪', category: 'Blood Draw' },
    { id: 'tube-gray', name: 'Gray top tube', icon: '🧪', category: 'Blood Draw' },
    { id: 'blood-culture-bottles', name: 'Blood culture bottles', icon: '🧪', category: 'Blood Draw' },
    { id: 'abg-syringe', name: 'ABG syringe', icon: '💉', category: 'Blood Draw' },
    // Safety
    { id: 'sharps-container', name: 'Sharps container', icon: '🗑️', category: 'Safety' },
    { id: 'biohazard-bag', name: 'Biohazard bag', icon: '⚠️', category: 'Safety' },
    // Misc
    { id: 'tissues', name: 'Tissues', icon: '🧻', category: 'Misc' },
    { id: 'chux-pad', name: 'Chux/underpad', icon: '📄', category: 'Misc' },
    { id: 'pillow-positioning', name: 'Positioning pillow/roll', icon: '🛏️', category: 'Misc' },
    { id: 'marker-skin', name: 'Skin marker', icon: '✏️', category: 'Misc' },
    { id: 'specimen-cup', name: 'Specimen cup', icon: '🥤', category: 'Misc' },
];

const SUPPLY_CATEGORIES = ['All','PPE','Antiseptics','Drapes','Anesthetics','Syringes','Needles','IV Supplies','Central Lines','Arterial Lines','Airway','Suction','Chest Tubes','Urinary','GI Tubes','Wound Care','Sutures','Scalpels','LP Supplies','Drainage','Blood Draw','Safety','Misc'];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { SUPPLY_CLOSET, SUPPLY_CATEGORIES };
}
