/* emr-data/handoff-data.js — ED-to-Floor Structured Handoffs
 * Rich I-PASS handoff data used by night-float.html and admissions.html.
 * Each handoff includes acuity, vitals, orders, labs, watchouts, etc.
 */
var HANDOFF_DATA = window.HANDOFF_DATA || {};
HANDOFF_DATA.handoffs = {
  "stemi-v1": {
    caseId:"stemi-v1", workingDx:"ST-Elevation MI, anterior",
    oneLiner:"58-year-old male with crushing chest pain radiating to left arm, ST elevation V1-V4, troponin rising",
    acuity:{esi:1,level:"critical"},
    bedAssignment:"CCU — Room 812",
    lastVitals:"BP 148/88, HR 92, RR 20, Temp 37.1C, SpO2 96%, Pain 9/10",
    edCourse:"Presented 45 min ago with acute substernal chest pain. ECG showed ST elevation V1-V4. Cath lab activated, aspirin 325 and ticagrelor loaded. Heparin bolus given.",
    completedOrders:["Aspirin 325mg PO","Ticagrelor 180mg PO","Heparin 60u/kg bolus then 12u/kg/hr drip","Morphine 4mg IV PRN","Metoprolol 5mg IV x1"],
    activeIVs:["Heparin drip at 1000u/hr","NS at 75mL/hr"],
    homeMeds:["Lisinopril 10mg daily","Atorvastatin 40mg daily","Metformin 1000mg BID"],
    pendingItems:["Cath lab ETA 15 min","Serial troponins q6h","Echocardiogram post-cath","Cardiology consult following"],
    watchOuts:["Door-to-balloon time critical — cath lab must happen within 90 min","Watch for cardiogenic shock, arrhythmia (VT/VF)","If BP drops <90 systolic, start dobutamine and call cardiology STAT"],
    keyLabs:["Troponin-I 2.4 ng/mL (rising)","BNP 580 pg/mL","Cr 1.1","K 4.2","Glucose 186"],
    keyImaging:["CXR: mild pulmonary congestion, no consolidation","ECG: ST elevation V1-V4, reciprocal changes II/III/aVF"],
    disposition:"Admit to CCU. Post-cath monitoring. Dual antiplatelet therapy.",
    familyUpdate:"Wife at bedside, aware of cath plan. Very anxious.",
    codeStatus:"Full code"
  },
  "anaphylaxis": {
    caseId:"anaphylaxis", workingDx:"Anaphylaxis, shellfish",
    oneLiner:"27-year-old female with anaphylaxis after shellfish exposure — lip/tongue swelling, diffuse urticaria, hypotension",
    acuity:{esi:1,level:"critical"},
    bedAssignment:"ED Resus — Room 1",
    lastVitals:"BP 88/52, HR 128, RR 28, Temp 36.8C, SpO2 91%, Pain 6/10",
    edCourse:"Ate shrimp at restaurant 30 min ago. Developed lip swelling, diffuse hives, throat tightness, then lightheadedness. EMS gave IM epi in field. Repeat epi given in ED. Now on epi drip.",
    completedOrders:["Epinephrine 0.3mg IM x2","Diphenhydramine 50mg IV","Famotidine 20mg IV","Methylprednisolone 125mg IV","2L NS bolus"],
    activeIVs:["Epinephrine drip 0.1 mcg/kg/min","NS at 250mL/hr"],
    homeMeds:["Albuterol PRN","OCP"],
    pendingItems:["Tryptase level (drawn)","Observe 6-8h minimum for biphasic reaction","Allergist referral before discharge","EpiPen prescription"],
    watchOuts:["Biphasic reaction can occur 4-12h after initial event","If BP drops again, uptitrate epi drip — max 0.5 mcg/kg/min","Airway swelling: have intubation equipment at bedside","Refractory: consider glucagon if on beta-blockers"],
    keyLabs:["Tryptase pending","CBC: WBC 12.4","BMP: normal","Lactate 2.8"],
    keyImaging:["CXR: clear, no pulmonary edema"],
    disposition:"Observe in ED/ICU step-down 6-8h. Prescribe EpiPen x2 and allergist follow-up.",
    familyUpdate:"Boyfriend present, very worried. Educated on EpiPen use.",
    codeStatus:"Full code"
  },
  "pneumonia": {
    caseId:"pneumonia", workingDx:"Community-acquired pneumonia",
    oneLiner:"62-year-old female with 5 days productive cough, fever to 102.8F, and hypoxia to 88% on room air",
    acuity:{esi:3,level:"moderate"},
    bedAssignment:"7 South — Room 712",
    lastVitals:"BP 118/72, HR 102, RR 24, Temp 39.3C, SpO2 92% on 2L NC, Pain 3/10",
    edCourse:"Progressively worsening cough with yellow sputum, fevers, and dyspnea on exertion. Found hypoxic in triage. CXR shows RLL consolidation. CURB-65 = 2. Started on antibiotics.",
    completedOrders:["Ceftriaxone 1g IV","Azithromycin 500mg IV","NS 1L bolus","Acetaminophen 1g PO","Albuterol neb x1"],
    activeIVs:["NS at 100mL/hr"],
    homeMeds:["Amlodipine 5mg daily","Omeprazole 20mg daily","Vitamin D 2000 IU daily"],
    pendingItems:["Blood cultures x2 (drawn, pending)","Sputum culture (pending)","Procalcitonin (pending)","Repeat CXR in 48h if not improving"],
    watchOuts:["If O2 requirement increases, check for empyema/effusion","Repeat vitals q4h — watch for sepsis criteria","If not improving in 48-72h, broaden antibiotics and CT chest"],
    keyLabs:["WBC 16.2 with left shift","Procalcitonin pending","BMP: Cr 0.9, BUN 22","Lactate 1.4"],
    keyImaging:["CXR: right lower lobe consolidation with air bronchograms, small R pleural effusion"],
    disposition:"Admit to medicine floor. Continue abx. Wean O2 as tolerated. Daily chest assessment.",
    familyUpdate:"Daughter called, aware of admission. Will visit in morning.",
    codeStatus:"Full code"
  },
  "dka-v1": {
    caseId:"dka-v1", workingDx:"Diabetic ketoacidosis",
    oneLiner:"22-year-old male with new-onset T1DM presenting with nausea, vomiting, Kussmaul breathing, glucose 480, pH 7.12",
    acuity:{esi:2,level:"critical"},
    bedAssignment:"ICU Step-down — Room 504",
    lastVitals:"BP 102/64, HR 118, RR 32, Temp 36.7C, SpO2 98%, Pain 5/10",
    edCourse:"3 days of polyuria, polydipsia, nausea, and vomiting. Found with glucose 480, pH 7.12, bicarb 8, anion gap 28. Insulin drip started. 2L NS given.",
    completedOrders:["Insulin drip 0.1 units/kg/hr","NS 2L bolus then 250mL/hr","Potassium 40mEq IV (K was 4.8, will drop)","Phosphate replacement pending level","Anti-emetic: ondansetron 4mg IV"],
    activeIVs:["Insulin drip 0.1 u/kg/hr","D5 half-NS at 250mL/hr (when glucose <250)","KCl 20mEq/hr via central line"],
    homeMeds:["None — new diagnosis"],
    pendingItems:["BMP q2h","Transition to SQ insulin when: gap closed, bicarb >18, patient eating, pH >7.3","Endocrine consult for insulin education","A1c pending","Lipase pending (rule out pancreatitis)"],
    watchOuts:["K will DROP with insulin — must be >3.3 before starting insulin, replete aggressively","Watch for cerebral edema (AMS, headache) — rare in adults but possible","Anion gap trend is the key metric, not glucose","DO NOT stop insulin drip until gap is closed AND overlap with SQ insulin x2h"],
    keyLabs:["Glucose 480","pH 7.12, pCO2 18","Bicarb 8, AG 28","K 4.8 (will drop)","BUN 32, Cr 1.6 (prerenal)","Beta-hydroxybutyrate 6.8"],
    keyImaging:["CXR: clear"],
    disposition:"ICU step-down. Q2h BMPs. Insulin drip until gap closure. Endocrine consult for new T1DM education.",
    familyUpdate:"Parents en route from out of state. Very concerned about new diabetes diagnosis.",
    codeStatus:"Full code"
  },
  "sepsisseptic-shock": {
    caseId:"sepsisseptic-shock", workingDx:"Septic shock — urinary source",
    oneLiner:"69-year-old male with fever 103.2F, hypotension, and altered mental status — urine source suspected",
    acuity:{esi:1,level:"critical"},
    bedAssignment:"MICU — Room 302",
    lastVitals:"BP 78/42, HR 122, RR 26, Temp 39.6C, SpO2 94% on 4L NC, Pain 4/10",
    edCourse:"Found confused at home by family. Fever, foul-smelling urine, chronic Foley catheter. ED: 30mL/kg crystalloid given, broad-spectrum antibiotics started, norepinephrine initiated for persistent hypotension post-fluids. Lactate 6.2.",
    completedOrders:["Vancomycin 25mg/kg IV loading dose","Piperacillin-tazobactam 4.5g IV","NS 30mL/kg (2.1L given)","Norepinephrine started at 5 mcg/min","Hydrocortisone 100mg IV (stress dose)","Foley removed, new Foley placed"],
    activeIVs:["Norepinephrine 8 mcg/min","NS at 150mL/hr","Vancomycin infusing"],
    homeMeds:["Tamsulosin 0.4mg daily","Metoprolol 25mg BID","Aspirin 81mg daily","Finasteride 5mg daily"],
    pendingItems:["Blood cultures x2 (drawn pre-abx)","Urine culture (drawn)","Lactate recheck at 2h","MAP goal >65 — may need vasopressin if norepi >15 mcg/min","Vancomycin trough in 24h"],
    watchOuts:["If MAP <65 on norepi >15 mcg/min, add vasopressin 0.04 units/min","Recheck lactate in 2h — if not clearing, consider inadequate source control","Watch for AKI — monitor UOP, Cr trending","Home metoprolol held — will blunt tachycardia response"],
    keyLabs:["WBC 22.4 with 18% bands","Lactate 6.2","Cr 2.1 (baseline 1.0)","BUN 45","Procalcitonin 28.4","UA: +++bacteria, +++WBC, nitrite positive"],
    keyImaging:["CXR: no infiltrate","CT abdomen/pelvis: bilateral hydronephrosis, Foley in place, no abscess"],
    disposition:"MICU. Aggressive fluid resuscitation. Pressors. Abx per ID recs. Monitor UOP closely.",
    familyUpdate:"Daughter is healthcare proxy. Updated by phone. DNR/DNI per prior documentation — VERIFY with family.",
    codeStatus:"DNR/DNI per chart — confirm with family"
  },
  "chf-exacerbation": {
    caseId:"chf-exacerbation", workingDx:"Acute decompensated heart failure",
    oneLiner:"72-year-old male with worsening dyspnea, orthopnea, 10-lb weight gain over 2 weeks, and bilateral LE edema",
    acuity:{esi:3,level:"moderate"},
    bedAssignment:"5 North — Room 518",
    lastVitals:"BP 162/98, HR 96, RR 24, Temp 36.6C, SpO2 90% on 3L NC, Pain 2/10",
    edCourse:"Ran out of furosemide 2 weeks ago. Progressive dyspnea, can't lie flat, 3-pillow orthopnea. BNP 1840. CXR with bilateral pleural effusions and pulmonary congestion. Given furosemide 40mg IV with good UOP.",
    completedOrders:["Furosemide 40mg IV x1 (produced 800mL in 2h)","Potassium 20mEq PO (K 3.6 post-diuresis)","Metoprolol 12.5mg PO (held if SBP <100)","Daily weights ordered","Strict I/O"],
    activeIVs:["Hep lock only — fluid restrict 1.5L/day"],
    homeMeds:["Furosemide 40mg BID (ran out)","Lisinopril 20mg daily","Carvedilol 12.5mg BID","Spironolactone 25mg daily","Atorvastatin 80mg daily","Warfarin (for AFib)"],
    pendingItems:["Furosemide 40mg IV q12h — reassess UOP and daily weight","Echocardiogram in AM (last EF 25%)","BMP in AM (watch K and Cr with diuresis)","Cardiology consult","Dietary consult for low-sodium education","INR in AM for warfarin dosing"],
    watchOuts:["Monitor K aggressively with diuresis — replace if <4.0","Watch Cr — if bumps >0.5 from baseline, hold diuresis and call cardiology","If SBP <100, hold metoprolol and lisinopril","Strict 1.5L fluid restriction — patient tends to drink a lot at night"],
    keyLabs:["BNP 1840","K 3.6 (post-diuresis)","Cr 1.4 (baseline 1.2)","Na 134","INR 2.3","Mg 1.8"],
    keyImaging:["CXR: bilateral pleural effusions, vascular congestion, cardiomegaly","ECG: atrial fibrillation, rate controlled, LVH"],
    disposition:"Admit to telemetry floor. Aggressive IV diuresis. Echo in AM. Cardiology consult.",
    familyUpdate:"Wife at bedside. Aware that he stopped taking his medications. Frustrated but supportive.",
    codeStatus:"Full code"
  },
  "copd-v1": {
    caseId:"copd-v1", workingDx:"COPD exacerbation",
    oneLiner:"67-year-old female with worsening dyspnea and productive cough x3 days, increased O2 requirement, and wheezing",
    acuity:{esi:3,level:"moderate"},
    bedAssignment:"6 North — Room 622",
    lastVitals:"BP 142/82, HR 98, RR 22, Temp 37.2C, SpO2 90% on 3L NC, Pain 2/10",
    edCourse:"Chronic COPD, 40-pack-year smoking history. 3 days of worsening cough with green sputum. Uses 2L home O2. Now requiring 3L. Given nebs and IV steroids in ED.",
    completedOrders:["Albuterol/ipratropium neb x3","Methylprednisolone 125mg IV","Azithromycin 500mg PO","NS 500mL bolus"],
    activeIVs:["NS at 75mL/hr"],
    homeMeds:["Tiotropium 18mcg daily","Fluticasone/salmeterol 250/50 BID","Albuterol PRN","Home O2 2L NC","Lisinopril 10mg daily"],
    pendingItems:["Sputum culture (if able to produce)","ABG in AM","Continue scheduled nebs q4h","Transition to PO prednisone 40mg x5 days","Respiratory therapy consult"],
    watchOuts:["If O2 requirement >6L or worsening work of breathing — ABG and consider BiPAP","Watch for CO2 retention — this patient is a chronic retainer, target SpO2 88-92%","Do NOT over-oxygenate — can worsen hypercapnia"],
    keyLabs:["WBC 11.8","ABG: pH 7.36, pCO2 52, pO2 62 on 3L (chronic retention)","BMP: normal","BNP 120 (rules out CHF)"],
    keyImaging:["CXR: hyperinflated lungs, flattened diaphragms, no focal consolidation"],
    disposition:"Admit to medicine floor. Scheduled nebs. IV steroids transitioning to PO. O2 target 88-92%.",
    familyUpdate:"Lives alone. Neighbor drove her in. Social work consulted for home safety evaluation.",
    codeStatus:"Full code"
  },
  "stroke-v1": {
    caseId:"stroke-v1", workingDx:"Acute ischemic stroke — left MCA territory",
    oneLiner:"72-year-old male with sudden-onset right-sided weakness and slurred speech 45 min ago, known AFib, INR subtherapeutic",
    acuity:{esi:1,level:"critical"},
    bedAssignment:"Neuro ICU — Room 210",
    lastVitals:"BP 186/102, HR 88 irreg, RR 18, Temp 37.0C, SpO2 97%, Pain 0/10",
    edCourse:"Wife noticed slurred speech and right arm weakness at dinner. Last known well 1 hour ago. NIHSS 14. CT head: no hemorrhage. CTA: left MCA M1 occlusion. tPA administered. Thrombectomy planned.",
    completedOrders:["Alteplase (tPA) 0.9mg/kg IV (10% bolus, 90% over 1h)","Nicardipine drip for BP <180/105 post-tPA","NPO","HOB 30 degrees","Neurology at bedside"],
    activeIVs:["tPA infusion (remaining 50 min)","Nicardipine drip at 5mg/hr","NS at 75mL/hr"],
    homeMeds:["Warfarin 5mg daily (INR was only 1.4)","Metoprolol 50mg BID","Atorvastatin 80mg daily","Amlodipine 10mg daily"],
    pendingItems:["Thrombectomy — neurointerventional team mobilized","Post-tPA neuro checks q15min x2h, then q30min x6h","Repeat CT head at 24h (or sooner if decline)","Swallow evaluation before any PO intake","PT/OT consult in AM"],
    watchOuts:["ANY neurologic decline — STAT CT head (rule out hemorrhagic conversion)","BP must stay <180/105 for 24h post-tPA — do NOT let it spike","NO anticoagulation or antiplatelet for 24h post-tPA","Strict NPO until speech pathology clears swallow","If NIHSS worsens by ≥4 points, STAT CT and call neuro"],
    keyLabs:["INR 1.4 (subtherapeutic on warfarin)","Glucose 142","Cr 1.0","Platelets 198K","PT 16.2"],
    keyImaging:["CT head: no acute hemorrhage, no midline shift","CTA: left MCA M1 occlusion","CT perfusion: large penumbra, small core — good candidate for intervention"],
    disposition:"Neuro ICU. Complete tPA infusion. Thrombectomy pending. Strict neuro checks and BP management.",
    familyUpdate:"Wife at bedside. Very frightened. Neurology spoke with her about tPA risks and thrombectomy plan.",
    codeStatus:"Full code"
  },
  "appendicitis-v1": {
    caseId:"appendicitis-v1", workingDx:"Acute appendicitis",
    oneLiner:"28-year-old male with 18h of periumbilical pain migrating to RLQ, fever, and elevated WBC",
    acuity:{esi:3,level:"moderate"},
    bedAssignment:"Surgical Floor — Room 408",
    lastVitals:"BP 128/78, HR 94, RR 18, Temp 38.4C, SpO2 99%, Pain 7/10",
    edCourse:"Classic appendicitis presentation with migration of pain. CT abdomen confirms acute appendicitis without perforation. Surgery consulted — OR scheduled for morning. NPO, antibiotics started.",
    completedOrders:["Cefoxitin 2g IV","Morphine 4mg IV x1","Ondansetron 4mg IV","NS 1L bolus","NPO after midnight"],
    activeIVs:["NS at 125mL/hr"],
    homeMeds:["None"],
    pendingItems:["OR scheduled for 0730 — laparoscopic appendectomy","Surgical consent obtained","NPO strictly enforced","Pre-op labs: CBC, BMP, T&S — all done"],
    watchOuts:["If pain suddenly worsens or fever spikes — may indicate perforation, call surgery STAT","Keep NPO for OR — no exceptions","If needs additional pain meds overnight, morphine 2-4mg IV q4h PRN"],
    keyLabs:["WBC 14.8 with left shift","BMP: normal","Lipase: normal","UA: normal"],
    keyImaging:["CT abdomen/pelvis: dilated appendix 12mm with periappendiceal fat stranding, no perforation, no abscess"],
    disposition:"Surgical floor. NPO for OR in AM. Continue antibiotics. Pain management overnight.",
    familyUpdate:"Parents aware. Mother coming in morning for surgery.",
    codeStatus:"Full code"
  },
  "pe-v1": {
    caseId:"pe-v1", workingDx:"Pulmonary embolism — submassive",
    oneLiner:"34-year-old female with acute pleuritic chest pain, tachycardia, and hypoxia — on OCPs, recent long flight",
    acuity:{esi:2,level:"critical"},
    bedAssignment:"ICU Step-down — Room 506",
    lastVitals:"BP 108/68, HR 112, RR 24, Temp 37.0C, SpO2 92% on 4L NC, Pain 7/10",
    edCourse:"Returned from 12h flight 3 days ago. Acute onset pleuritic chest pain and dyspnea. D-dimer >5000. CTA: bilateral PE with RV strain. Troponin mildly elevated. Heparin started.",
    completedOrders:["Heparin 80u/kg bolus then 18u/kg/hr drip","Morphine 2mg IV x1 for pleuritic pain","NS 500mL bolus","OCPs discontinued"],
    activeIVs:["Heparin drip (target aPTT 60-80)","NS at 75mL/hr"],
    homeMeds:["Combined OCP (ethinyl estradiol/norgestimate)","Sertraline 50mg daily"],
    pendingItems:["aPTT in 6h — titrate heparin per protocol","Echo in AM to assess RV function","Lower extremity dopplers","Transition to DOAC (rivaroxaban) when stable","Hematology referral (young patient with unprovoked PE — thrombophilia workup)"],
    watchOuts:["If BP drops <90 systolic — consider massive PE protocol, call STAT for thrombolytics","Monitor for RV failure: rising troponin, JVD, hepatomegaly","Keep head of bed elevated, supplemental O2 to keep SpO2 >92%","Do NOT give fluids aggressively — RV is preload-sensitive in PE"],
    keyLabs:["D-dimer >5000","Troponin-I 0.18 (mildly elevated — RV strain)","BNP 340","BMP: normal","CBC: normal"],
    keyImaging:["CTA chest: bilateral pulmonary emboli, saddle embolus at main PA bifurcation, RV/LV ratio 1.3 (RV strain)","ECG: sinus tach, S1Q3T3 pattern, T-wave inversions V1-V3"],
    disposition:"ICU step-down. Heparin drip. Monitor hemodynamics closely. Echo in AM.",
    familyUpdate:"Boyfriend present. Both very anxious. Educated on anticoagulation and OCP discontinuation.",
    codeStatus:"Full code"
  },
  "acute-pancreatitis": {
    caseId:"acute-pancreatitis", workingDx:"Acute pancreatitis — gallstone",
    oneLiner:"48-year-old female with severe epigastric pain radiating to back, nausea/vomiting, lipase 2400",
    acuity:{esi:3,level:"moderate"},
    bedAssignment:"5 South — Room 528",
    lastVitals:"BP 132/78, HR 98, RR 20, Temp 37.8C, SpO2 98%, Pain 8/10",
    edCourse:"Acute onset epigastric pain after fatty meal. Lipase 2400. RUQ US shows gallstones with CBD 8mm. No cholangitis. Aggressive fluids and pain control started.",
    completedOrders:["NS 2L bolus (LR preferred)","Hydromorphone 0.5mg IV q4h PRN","Ondansetron 4mg IV q6h PRN","Acetaminophen 1g IV","NPO"],
    activeIVs:["LR at 200mL/hr (aggressive hydration)"],
    homeMeds:["Omeprazole 20mg daily","Metformin 500mg BID","OCP"],
    pendingItems:["MRCP in AM if CBD remains dilated","GI consult for ERCP if CBD stone confirmed","Advance diet when pain improves and tolerating clear liquids","Surgical consult for cholecystectomy (same admission vs outpatient)"],
    watchOuts:["Monitor for organ failure: check Cr, O2 requirement, mental status","If fever develops or WBC spikes — concern for infected necrosis, get CT","Ranson criteria at 48h","Pain control is critical — undertreated pain worsens outcomes"],
    keyLabs:["Lipase 2400","AST 220, ALT 310 (transaminitis suggests gallstone etiology)","Total bili 2.1","WBC 13.2","BUN 18, Cr 0.8","Triglycerides normal"],
    keyImaging:["RUQ US: multiple gallstones, CBD 8mm (dilated), no pericholecystic fluid","CXR: small left pleural effusion"],
    disposition:"Admit medicine floor. Aggressive IVF. Pain management. GI and surgery consults.",
    familyUpdate:"Husband aware. Will come in morning.",
    codeStatus:"Full code"
  },
  "neutropenic-fever": {
    caseId:"neutropenic-fever", workingDx:"Febrile neutropenia — post-chemotherapy",
    oneLiner:"63-year-old female with AML on induction chemo, ANC 120, fever 102.4F, no clear source",
    acuity:{esi:2,level:"critical"},
    bedAssignment:"Oncology — Room 910 (neutropenic precautions)",
    lastVitals:"BP 98/62, HR 108, RR 22, Temp 39.1C, SpO2 96%, Pain 3/10",
    edCourse:"Day 10 of induction chemo. Developed rigors and fever at home. ANC 120. No obvious source on exam — port site clean, no oral lesions, lungs clear, no perirectal abscess. Broad-spectrum antibiotics started within 30 min of arrival.",
    completedOrders:["Cefepime 2g IV STAT","Vancomycin 25mg/kg IV (port access concern)","Blood cultures x2 (peripheral + port)","NS 1L bolus","Acetaminophen 650mg PO"],
    activeIVs:["NS at 125mL/hr","Cefepime q8h","Vancomycin q12h"],
    homeMeds:["Acyclovir prophylaxis","Fluconazole prophylaxis","Ondansetron PRN"],
    pendingItems:["Blood cultures pending (48h)","CXR done — clear","If still febrile at 72h on abx, add antifungal (micafungin)","Daily CBC — watch for ANC recovery","Oncology following — Dr. Rodriguez"],
    watchOuts:["Febrile neutropenia = medical emergency — any hemodynamic instability, escalate immediately","If new pulmonary symptoms, CT chest for fungal infection","NO rectal temps, NO suppositories, NO IM injections","Strict neutropenic precautions — hand hygiene, masks for visitors, no fresh flowers/fruit"],
    keyLabs:["WBC 0.4, ANC 120","Hgb 7.8 (transfuse if <7)","Plt 42K (transfuse if <10 or bleeding)","Cr 0.9","LFTs: mildly elevated ALT 62"],
    keyImaging:["CXR: clear, no infiltrate","Port CXR: line in good position"],
    disposition:"Admit to oncology floor with neutropenic precautions. Broad-spectrum abx. Monitor closely.",
    familyUpdate:"Husband at bedside. Both understand the seriousness. Oncology team has spoken with them.",
    codeStatus:"Full code — confirmed with patient and oncology"
  }
};
HANDOFF_DATA.ipass = {
  illness:"Acute / Chronic / Stable",
  patientSummary:"One-liner with pertinent details",
  actionList:"Pending tasks and follow-ups",
  situationAwareness:"What to watch for overnight",
  synthesis:"Big picture plan and contingencies"
};
