const cases = [
    // CARDIOLOGY
    {name:"Acute Coronary Syndrome",file:"acs-expanded.html",category:"cardiology",icon:"❤️",type:"standard"},
    {name:"ACS Adventure",file:"acs-expanded-adventure.html",category:"cardiology",icon:"❤️",type:"adventure"},
    {name:"Atrial Fibrillation",file:"afib-expanded.html",category:"cardiology",icon:"💓",type:"standard"},
    {name:"AFib Adventure",file:"afib-expanded-adventure.html",category:"cardiology",icon:"💓",type:"adventure"},
    {name:"Heart Failure",file:"heart-failure-expanded.html",category:"cardiology",icon:"💔",type:"standard"},
    {name:"Heart Failure Adventure",file:"heart-failure-expanded-adventure.html",category:"cardiology",icon:"💔",type:"adventure"},
    {name:"SVT & WPW",file:"svt-wpw-expanded.html",category:"cardiology",icon:"⚡",type:"standard"},
    {name:"Syncope",file:"syncope-expanded.html",category:"cardiology",icon:"😵",type:"standard"},
    // PULMONARY
    {name:"Pulmonary Embolism",file:"pe-expanded.html",category:"pulmonary",icon:"🫁",type:"standard"},
    {name:"PE Adventure",file:"pe-expanded-adventure.html",category:"pulmonary",icon:"🫁",type:"adventure"},
    {name:"COPD Exacerbation",file:"copd-exacerbation-expanded.html",category:"pulmonary",icon:"💨",type:"standard"},
    {name:"COPD Adventure",file:"copd-expanded-adventure.html",category:"pulmonary",icon:"💨",type:"adventure"},
    {name:"Pneumonia",file:"pneumonia-expanded.html",category:"pulmonary",icon:"🦠",type:"standard"},
    {name:"Asthma Exacerbation",file:"asthma-exacerbation-expanded.html",category:"pulmonary",icon:"🌬️",type:"standard"},
    {name:"Asthma Phenotyping",file:"asthma-phenotyping-expanded.html",category:"pulmonary",icon:"🌬️",type:"standard"},
    {name:"Asthma Biologics",file:"asthma-biologics-expanded.html",category:"pulmonary",icon:"💉",type:"standard"},
    {name:"Tension Pneumothorax",file:"tension-ptx-expanded.html",category:"pulmonary",icon:"💥",type:"standard"},
    // GI
    {name:"GI Bleed",file:"gi-bleed-expanded.html",category:"gi",icon:"🩸",type:"standard"},
    {name:"GI Bleed Adventure",file:"gi-bleed-expanded-adventure.html",category:"gi",icon:"🩸",type:"adventure"},
    {name:"Acute Liver Failure",file:"alf-expanded.html",category:"gi",icon:"🫀",type:"standard"},
    {name:"Pancreatitis",file:"pancreatitis-expanded.html",category:"gi",icon:"🍽️",type:"standard"},
    {name:"Cholecystitis",file:"cholecystitis-expanded.html",category:"gi",icon:"🟡",type:"standard"},
    {name:"Appendicitis",file:"appendicitis-expanded.html",category:"gi",icon:"📍",type:"standard"},
    {name:"SBO",file:"sbo-expanded.html",category:"gi",icon:"🔴",type:"standard"},
    {name:"Acute Abdomen",file:"acute-abdomen-expanded.html",category:"gi",icon:"🤢",type:"standard"},
    {name:"C. diff",file:"cdiff-expanded.html",category:"gi",icon:"🦠",type:"standard"},
    // NEUROLOGY
    {name:"Stroke",file:"stroke-expanded.html",category:"neurology",icon:"🧠",type:"standard"},
    {name:"Stroke Adventure",file:"stroke-expanded-adventure.html",category:"neurology",icon:"🧠",type:"adventure"},
    {name:"Status Epilepticus",file:"status-epilepticus-expanded.html",category:"neurology",icon:"⚡",type:"standard"},
    {name:"Febrile Seizure",file:"febrile-seizure-expanded.html",category:"neurology",icon:"🌡️",type:"standard"},
    {name:"Meningitis",file:"meningitis-expanded.html",category:"neurology",icon:"🦠",type:"standard"},
    {name:"Meningitis Adventure",file:"meningitis-expanded-adventure.html",category:"neurology",icon:"🦠",type:"adventure"},
    {name:"Meningitis Dual",file:"meningitis-expanded-dual-adventure.html",category:"neurology",icon:"🦠",type:"dual"},
    {name:"SAH",file:"sah-expanded.html",category:"neurology",icon:"🔴",type:"standard"},
    {name:"TBI & ICP",file:"tbi-icp-expanded.html",category:"neurology",icon:"🤕",type:"standard"},
    // ALLERGY/IMMUNOLOGY
    {name:"Anaphylaxis",file:"anaphylaxis-expanded.html",category:"allergy",icon:"🌸",type:"standard"},
    {name:"Anaphylaxis Adventure",file:"anaphylaxis-expanded-adventure.html",category:"allergy",icon:"🌸",type:"adventure"},
    {name:"Anaphylaxis Dual",file:"anaphylaxis-expanded-dual-adventure.html",category:"allergy",icon:"🌸",type:"dual"},
    {name:"Food Allergy",file:"food-allergy-expanded.html",category:"allergy",icon:"🥜",type:"standard"},
    {name:"Food Allergy Adventure",file:"food-allergy-expanded-adventure.html",category:"allergy",icon:"🥜",type:"adventure"},
    {name:"Drug Allergy",file:"drug-allergy-expanded.html",category:"allergy",icon:"💊",type:"standard"},
    {name:"Drug Allergy Adventure",file:"drug-allergy-expanded-adventure.html",category:"allergy",icon:"💊",type:"adventure"},
    {name:"Venom Allergy",file:"venom-allergy-expanded.html",category:"allergy",icon:"🐝",type:"standard"},
    {name:"Venom Allergy Adventure",file:"venom-allergy-expanded-adventure.html",category:"allergy",icon:"🐝",type:"adventure"},
    {name:"Urticaria/Angioedema",file:"urticaria-angioedema-expanded.html",category:"allergy",icon:"🔴",type:"standard"},
    {name:"Urticaria Adventure",file:"urticaria-expanded-adventure.html",category:"allergy",icon:"🔴",type:"adventure"},
    {name:"Angioedema Adventure",file:"angioedema-expanded-adventure.html",category:"allergy",icon:"😮",type:"adventure"},
    {name:"HAE",file:"hae-expanded.html",category:"allergy",icon:"🧬",type:"standard"},
    {name:"Allergic Rhinitis",file:"allergic-rhinitis-expanded.html",category:"allergy",icon:"🤧",type:"standard"},
    {name:"Immunodeficiency",file:"immunodeficiency-expanded.html",category:"allergy",icon:"🛡️",type:"standard"},
    {name:"Eosinophilia",file:"eosinophilia-expanded.html",category:"allergy",icon:"🔬",type:"standard"},
    {name:"Mast Cell",file:"mast-cell-expanded.html",category:"allergy",icon:"⚠️",type:"standard"},
    {name:"Penicillin Delabeling",file:"penicillin-delabeling-expanded.html",category:"allergy",icon:"💊",type:"standard"},
    {name:"Venom VIT",file:"venom-vit-expanded.html",category:"allergy",icon:"💉",type:"standard"},
    // INFECTIOUS
    {name:"Sepsis",file:"sepsis-expanded.html",category:"infectious",icon:"🦠",type:"standard"},
    {name:"Sepsis Adventure",file:"sepsis-expanded-adventure.html",category:"infectious",icon:"🦠",type:"adventure"},
    {name:"Sepsis Dual",file:"sepsis-expanded-dual-adventure.html",category:"infectious",icon:"🦠",type:"dual"},
    {name:"Cellulitis/NecFasc",file:"cellulitis-necfasc-expanded.html",category:"infectious",icon:"🔴",type:"standard"},
    {name:"Pyelonephritis",file:"pyelonephritis-expanded.html",category:"infectious",icon:"🫘",type:"standard"},
    {name:"Neutropenic Fever",file:"neutropenic-fever-expanded.html",category:"infectious",icon:"🌡️",type:"standard"},
    {name:"DFI",file:"dfi-expanded.html",category:"infectious",icon:"🦶",type:"standard"},
    // ENDOCRINE
    {name:"DKA",file:"dka-expanded.html",category:"endocrine",icon:"🍬",type:"standard"},
    {name:"DKA Adventure",file:"dka-expanded-adventure.html",category:"endocrine",icon:"🍬",type:"adventure"},
    {name:"Peds DKA",file:"peds-dka-expanded.html",category:"endocrine",icon:"🧒",type:"standard"},
    {name:"HHS vs DKA",file:"hhs-dka-comparison-expanded.html",category:"endocrine",icon:"📊",type:"standard"},
    {name:"Thyroid Storm",file:"thyroid-storm-expanded.html",category:"endocrine",icon:"🦋",type:"standard"},
    {name:"Adrenal Crisis",file:"adrenal-crisis-expanded.html",category:"endocrine",icon:"⚡",type:"standard"},
    {name:"Hypoglycemia",file:"hypoglycemia-expanded.html",category:"endocrine",icon:"📉",type:"standard"},
    // RENAL
    {name:"AKI",file:"aki-expanded.html",category:"renal",icon:"🫘",type:"standard"},
    {name:"AKI Adventure",file:"aki-expanded-adventure.html",category:"renal",icon:"🫘",type:"adventure"},
    {name:"AKI Workup",file:"aki-workup-expanded.html",category:"renal",icon:"🔬",type:"standard"},
    {name:"Hyperkalemia",file:"hyperkalemia-expanded.html",category:"renal",icon:"⚡",type:"standard"},
    {name:"Hyponatremia",file:"hyponatremia-expanded.html",category:"renal",icon:"💧",type:"standard"},
    {name:"Electrolytes",file:"electrolyte-emergencies-expanded.html",category:"renal",icon:"⚗️",type:"standard"},
    {name:"Rhabdomyolysis",file:"rhabdomyolysis-expanded.html",category:"renal",icon:"💪",type:"standard"},
    // HEME/ONC
    {name:"DIC",file:"dic-expanded.html",category:"heme",icon:"🩸",type:"standard"},
    {name:"TTP-HUS",file:"ttp-hus-expanded.html",category:"heme",icon:"🔴",type:"standard"},
    {name:"DVT",file:"dvt-expanded.html",category:"heme",icon:"🦵",type:"standard"},
    {name:"Shock",file:"shock-expanded.html",category:"heme",icon:"📉",type:"standard"},
    // PSYCH
    {name:"Depression",file:"depression-expanded.html",category:"psych",icon:"😔",type:"standard"},
    {name:"Bipolar",file:"bipolar-disorder-expanded.html",category:"psych",icon:"🔄",type:"standard"},
    {name:"Psychosis",file:"psychosis-expanded.html",category:"psych",icon:"💭",type:"standard"},
    {name:"Delirium",file:"delirium-expanded.html",category:"psych",icon:"😵",type:"standard"},
    // OB/GYN
    {name:"Ectopic Pregnancy",file:"ectopic-pregnancy-expanded.html",category:"obgyn",icon:"👶",type:"standard"},
    {name:"Preeclampsia",file:"preeclampsia-expanded.html",category:"obgyn",icon:"🤰",type:"standard"},
    {name:"PPH",file:"pph-expanded.html",category:"obgyn",icon:"🩸",type:"standard"},
    {name:"Placental Abruption",file:"placental-abruption-expanded.html",category:"obgyn",icon:"⚠️",type:"standard"},
    {name:"PID/TOA",file:"pid-toa-expanded.html",category:"obgyn",icon:"🔴",type:"standard"},
    {name:"Ovarian Torsion",file:"ovarian-torsion-expanded.html",category:"obgyn",icon:"🔄",type:"standard"},
    // PEDS
    {name:"Kawasaki",file:"kawasaki-expanded.html",category:"peds",icon:"❤️",type:"standard"},
    {name:"Croup",file:"croup-expanded.html",category:"peds",icon:"🌬️",type:"standard"},
    {name:"Bronchiolitis",file:"bronchiolitis-expanded.html",category:"peds",icon:"👶",type:"standard"},
    {name:"Intussusception",file:"intussusception-expanded.html",category:"peds",icon:"🔴",type:"standard"},
    {name:"Pyloric Stenosis",file:"pyloric-stenosis-expanded.html",category:"peds",icon:"🤮",type:"standard"},
    // TOXICOLOGY
    {name:"Toxidromes",file:"toxidromes-expanded.html",category:"toxicology",icon:"☠️",type:"standard"},
    {name:"APAP Overdose",file:"apap-overdose-expanded.html",category:"toxicology",icon:"💊",type:"standard"},
    {name:"Opioid Overdose",file:"opioid-overdose-expanded.html",category:"toxicology",icon:"💉",type:"standard"},
    {name:"Alcohol Withdrawal",file:"alcohol-withdrawal-expanded.html",category:"toxicology",icon:"🍺",type:"standard"},
    // TRAUMA/EMERGENCY
    {name:"HTN Emergency",file:"htn-emergency-expanded.html",category:"trauma",icon:"📈",type:"standard"},
    {name:"HTN Emergency Adventure",file:"htn-emergency-expanded-adventure.html",category:"trauma",icon:"📈",type:"adventure"},
    {name:"Aortic Dissection",file:"aortic-dissection-expanded.html",category:"trauma",icon:"💔",type:"standard"},
    {name:"Spinal Cord Compression",file:"spinal-cord-compression-expanded.html",category:"trauma",icon:"🦴",type:"standard"},
    {name:"Chest Pain",file:"chest-pain-expanded.html",category:"trauma",icon:"💓",type:"standard"},
    // OTHER
    {name:"Acid-Base",file:"acid-base-expanded.html",category:"other",icon:"⚗️",type:"standard"},
    {name:"ACLS Rhythms",file:"acls-rhythms-expanded.html",category:"other",icon:"📈",type:"standard"},
    {name:"Rheum Emergencies",file:"rheum-emergencies-expanded.html",category:"other",icon:"🦴",type:"standard"},
    {name:"ENT Emergencies",file:"ent-emergencies-expanded.html",category:"other",icon:"👂",type:"standard"},
    {name:"Eye Emergencies",file:"eye-emergencies-expanded.html",category:"other",icon:"👁️",type:"standard"},
    {name:"Derm Emergencies",file:"dermatologic-emergencies-expanded.html",category:"other",icon:"🔴",type:"standard"},
    {name:"DRESS/SCAR",file:"dress-scar-expanded.html",category:"other",icon:"⚠️",type:"standard"},
    {name:"Contact Dermatitis",file:"contact-dermatitis-expanded.html",category:"other",icon:"🔴",type:"standard"},
    {name:"Atopic Dermatitis",file:"atopic-dermatitis-expanded.html",category:"other",icon:"🔴",type:"standard"}
];
