/* emr-data/guidelines-library.js
 * ReasonDx Central Guidelines Library — Allergy/Immunology
 * All sources are open-access, peer-reviewed, or society guidelines
 */
window.GUIDELINES_LIBRARY = {
anaphylaxis:[
{id:"GA2LEN-2025",title:"Anaphylaxis definition, overview, and clinical support tool: 2024 consensus report",authors:"Dribin TE, Muraro A, Camargo CA, Turner PJ, Wang J, et al.",journal:"J Allergy Clin Immunol",year:2025,doi:"10.1016/j.jaci.2025.01.021",url:"https://www.jacionline.org/article/S0091-6749(25)00072-7/fulltext",oa:true,cases:["anaphylaxis","anaphylaxis-v2","anaphylaxis-v3","anaphylaxis-v4","anaphylaxis-v5","severe-allergic-reaction","severe-allergic-reaction-v2","severe-allergic-reaction-v3"],validates:["Anaphylaxis diagnostic criteria","Epinephrine IM dosing","Biphasic reaction monitoring","Neffy nasal epinephrine"]},
{id:"WAO-2020",title:"World Allergy Organization anaphylaxis guidance 2020",authors:"Cardona V, Ansotegui IJ, Ebisawa M, et al.",journal:"World Allergy Organ J",year:2020,doi:"10.1016/j.waojou.2020.100472",pmcid:"PMC7607509",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC7607509/",oa:true,cases:["anaphylaxis","anaphylaxis-v2","anaphylaxis-v3","anaphylaxis-v4","anaphylaxis-v5","severe-allergic-reaction","severe-allergic-reaction-v2"],validates:["WAO diagnostic criteria","Epinephrine positioning","Cofactors: exercise, beta-blockers, ACE inhibitors"]},
{id:"JTFPP-Anaph-2023",title:"Anaphylaxis: A 2023 practice parameter update",authors:"Golden DBK, Wang J, Waserman S, et al.",journal:"Ann Allergy Asthma Immunol",year:2023,doi:"10.1016/j.anai.2023.09.015",url:"https://www.aaaai.org/Aaaai/media/Media-Library-PDFs/Allergist%20Resources/Statements%20and%20Practice%20Parameters/Anaphylaxis-Practice-Paramaters-2023.pdf",oa:true,cases:["anaphylaxis","anaphylaxis-v2","anaphylaxis-v3","anaphylaxis-v4","anaphylaxis-v5","severe-allergic-reaction","severe-allergic-reaction-v2","severe-allergic-reaction-v3"],validates:["Glucagon for beta-blocker patients","Tryptase measurement timing","0.1/0.15mg epi for infants","MCAS screening after anaphylaxis"]},
{id:"EAACI-Anaph-2021",title:"EAACI guidelines: Anaphylaxis (2021 update)",authors:"Muraro A, Worm M, Alviani C, et al.",journal:"Allergy",year:2022,doi:"10.1111/all.15032",pmcid:"PMC9285065",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9285065/",oa:true,cases:["anaphylaxis","anaphylaxis-v2","anaphylaxis-v3","anaphylaxis-v4","anaphylaxis-v5"],validates:["Discharge planning with EpiPen","Patient action plans","Allergist referral 4-6 weeks"]}
],
angioedema:[
{id:"WAO-HAE-2022",title:"International WAO/EAACI guideline for management of hereditary angioedema — 2021 revision",authors:"Maurer M, Magerl M, Betschel S, et al.",journal:"Allergy",year:2022,doi:"10.1111/all.15214",pmcid:"PMC9541881",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9541881/",oa:true,cases:["hereditary-angioedema","hereditary-angioedema-v2","acquired-c1esterase-inhibitor-deficiency","acquired-c1esterase-inhibitor-deficiency-v2"],validates:["HAE diagnosis: C4 screening, C1-INH level/function","C1q distinguishes acquired from hereditary","On-demand icatibant","Lanadelumab prophylaxis","Estrogen triggers: OCPs contraindicated"]},
{id:"ACE-AE-Byrd-2006",title:"ACE inhibitor-associated angioedema",authors:"Byrd JB, Adam A, Brown NJ.",journal:"Immunol Allergy Clin North Am",year:2006,doi:"10.1016/j.iac.2006.08.001",pmcid:"PMC4039077",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC4039077/",oa:true,cases:["ace-angioedema","ace-angioedema-v2"],validates:["3-5x higher risk in African Americans","Late-onset possible years after starting","Bradykinin mechanism","ARB cross-reactivity 2-10%","Icatibant for ACE angioedema"]},
{id:"Acquired-C1INH-2010",title:"Acquired angioedema",authors:"Cicardi M, Zanichelli A.",journal:"Allergy Asthma Clin Immunol",year:2010,doi:"10.1186/1710-1492-6-14",pmcid:"PMC2904712",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC2904712/",oa:true,cases:["acquired-c1esterase-inhibitor-deficiency","acquired-c1esterase-inhibitor-deficiency-v2"],validates:["C1q LOW in acquired, NORMAL in HAE","Anti-C1-INH antibodies","MGUS/lymphoproliferative association","Rituximab for refractory"]}
],
drugReactions:[
{id:"SCORTEN-2000",title:"SCORTEN: severity-of-illness score for toxic epidermal necrolysis",authors:"Bastuji-Garin S, Fouchard N, Bertocchi M, et al.",journal:"J Invest Dermatol",year:2000,doi:"10.1046/j.1523-1747.2000.00061.x",url:"https://pubmed.ncbi.nlm.nih.gov/10998259/",oa:true,cases:["sjs-ten","sjs-ten-v2","sjsten-overlap","sjsten-overlap-v2"],validates:["SCORTEN mortality prediction","7 clinical parameters","Score 2 = 12.1%, Score 3 = 35.3% mortality"]},
{id:"RegiSCAR-2013",title:"DRESS: results from the prospective RegiSCAR study",authors:"Kardaun SH, Sekula P, Valeyrie-Allanore L, et al.",journal:"Br J Dermatol",year:2013,doi:"10.1111/bjd.12501",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3667597/",oa:false,cases:["dress-syndrome","dress-syndrome-v2"],validates:["RegiSCAR score ≥5 = definite DRESS","HHV-6 reactivation","Organ involvement patterns","Slow steroid taper 8-12 weeks"],oa:true},
{id:"HLA-B5801-ACR-2020",title:"2020 ACR guideline for management of gout",authors:"FitzGerald JD, Dalbeth N, Mikuls T, et al.",journal:"Arthritis Care Res",year:2020,doi:"10.1002/acr.24180",pmcid:"PMC10563586",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC10563586/",oa:true,cases:["dress-syndrome-v2"],validates:["HLA-B*58:01 testing before allopurinol in SE Asian, Korean, African American patients"]},
{id:"DRESS-Autoimmunity-2019",title:"DRESS syndrome and long-term risk of autoimmunity",authors:"Chen YC, Chang CY, Cho YT, et al.",journal:"J Allergy Clin Immunol Pract",year:2019,doi:"10.1016/j.jaip.2018.08.004",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC6728016/",oa:false,cases:["dress-syndrome","dress-syndrome-v2"],validates:["Autoimmune thyroiditis ~40% post-DRESS","TSH monitoring at 3, 6, 12 months","Type 1 DM risk"],oa:true},
{id:"EM-HSV-Prevention",title:"Erythema multiforme: recognition, treatment, and prevention",authors:"Sokumbi O, Wetter DA.",journal:"Cleve Clin J Med",year:2012,doi:"10.3949/ccjm.79a.11118",url:"https://pubmed.ncbi.nlm.nih.gov/22473726/",oa:true,cases:["erythema-multiforme-major","erythema-multiforme-major-v2"],validates:["HSV triggers >70% recurrent EM","Valacyclovir 500mg daily prevents recurrence","EM vs SJS = different diseases"]}
],
urticaria:[
{id:"EAACI-Urticaria-2022",title:"EAACI/GA2LEN/EuroGuiDerm/APAAACI urticaria guideline",authors:"Zuberbier T, Abdul Latiff AH, et al.",journal:"Allergy",year:2022,doi:"10.1111/all.15090",url:"https://onlinelibrary.wiley.com/doi/10.1111/all.15090",oa:true,cases:["acute-urticaria","acute-urticaria-v2","chronic-spontaneous-urticaria","chronic-spontaneous-urticaria-v2","urticarial-vasculitis","urticarial-vasculitis-v2"],validates:["Wheals <24h = urticaria; >24h with bruising = biopsy for UV","UAS7 scoring","Step-up: sgAH → updose 4x → omalizumab → cyclosporine","Post-viral urticaria in children: no allergy testing needed"]}
],
drugAllergy:[
{id:"Drug-Allergy-PP-2022",title:"Drug allergy: A 2022 practice parameter update",authors:"Khan DA, Banerji A, Blumenthal KG, et al.",journal:"J Allergy Clin Immunol",year:2022,doi:"10.1016/j.jaci.2022.08.028",url:"https://www.jacionline.org/article/S0091-6749(22)01186-1/fulltext",oa:true,cases:["penicillin-allergy-delabeling","penicillin-allergy-delabeling-v2","drug-allergy-vancomycin-rms","drug-allergy-vancomycin-rms-v2","nsaid-hypersensitivity","nsaid-hypersensitivity-v2","severe-allergic-reaction-v3"],validates:["PCN skin testing for anaphylaxis history; direct challenge for remote benign reactions","Single-dose amoxicillin challenge for low-risk","Vancomycin RMS management","AERD aspirin desensitization protocol","Sulfonamide challenge protocols"]},
{id:"PCN-NEJM-2019",title:"Penicillin allergy",authors:"Castells M, Khan DA, Phillips EJ.",journal:"N Engl J Med",year:2019,doi:"10.1056/NEJMra1807761",url:"https://pubmed.ncbi.nlm.nih.gov/31826341/",oa:false,cases:["penicillin-allergy-delabeling","penicillin-allergy-delabeling-v2","drug-allergy-vancomycin-rms-v2","severe-allergic-reaction-v3"],validates:[">90% with PCN label NOT truly allergic",">80% lose sensitivity after 10 years","Morbilliform rash in children = usually viral exanthem","False PCN allergy → MRSA, C. diff, longer stays, higher mortality"]},
{id:"AERD-Review-2021",title:"Aspirin-exacerbated respiratory disease: comprehensive review",authors:"Laidlaw TM, Mullol J, Woessner KM, et al.",journal:"J Allergy Clin Immunol Pract",year:2021,doi:"10.1016/j.jaip.2020.09.016",pmcid:"PMC7855559",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC7855559/",oa:true,cases:["nsaid-hypersensitivity","nsaid-hypersensitivity-v2"],validates:["AERD triad","Aspirin desensitization 2-day protocol","Maintenance 650mg BID","Zileuton for AERD","Anosmia recovery 30-60%"]},
{id:"Vanc-RMS-2003",title:"Red man syndrome",authors:"Sivagnanam S, Deleu D.",journal:"Crit Care",year:2003,doi:"10.1186/cc1871",pmcid:"PMC270697",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC270697/",oa:true,cases:["drug-allergy-vancomycin-rms","drug-allergy-vancomycin-rms-v2"],validates:["RMS = histamine release, NOT IgE","Slow infusion ≥2h + premedication","NOT a true allergy"]}
],
foodAllergy:[
{id:"NIAID-FA-2010",title:"Guidelines for diagnosis and management of food allergy in the US",authors:"Boyce JA, Assa'ad A, Burks AW, et al.",journal:"J Allergy Clin Immunol",year:2010,doi:"10.1016/j.jaci.2010.10.008",pmcid:"PMC4241964",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC4241964/",oa:true,cases:["peanut-allergy-anaphylaxis","peanut-allergy-anaphylaxis-v2","food-allergy-oit-reaction","food-allergy-oit-reaction-v2","milk-allergy-infant","milk-allergy-infant-v2"],validates:["IgE-mediated food allergy criteria","Component testing (Ara h 2)","OFC as gold standard"]},
{id:"FPIES-Consensus-2017",title:"International consensus guidelines for FPIES: executive summary",authors:"Nowak-Wegrzyn A, Chehade M, Groetch ME, et al.",journal:"J Allergy Clin Immunol",year:2017,doi:"10.1016/j.jaci.2016.12.966",url:"https://www.jacionline.org/article/S0091-6749(17)30153-7/fulltext",oa:true,cases:["fpies-acute","fpies-acute-v2","fpies-chronic","fpies-chronic-v2"],validates:["FPIES criteria: major + minor","Ondansetron first-line (NOT epi)","Chronic FPIES: insidious FTT","Non-IgE, T-cell mediated","60% resolution by age 3-5"]},
{id:"EoE-AGA-2020",title:"AGA clinical practice update on dietary management of EoE",authors:"Hirano I, Chan ES, Rank MA, et al.",journal:"Gastroenterology",year:2020,doi:"10.1053/j.gastro.2020.02.038",pmcid:"PMC7286571",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC7286571/",oa:true,cases:["eoe-adult","eoe-adult-v2","eoe-pediatric","eoe-pediatric-v2"],validates:["≥15 eos/HPF diagnostic threshold","1-food (milk) elimination first-line","Swallowed budesonide/fluticasone","Repeat EGD 8-12 weeks"]},
{id:"DRACMA-2010",title:"WAO DRACMA: cow's milk allergy diagnosis",authors:"Fiocchi A, Brozek J, Schunemann H, et al.",journal:"World Allergy Organ J",year:2010,doi:"10.1097/WOX.0b013e3181defeb9",pmcid:"PMC3488907",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3488907/",oa:true,cases:["milk-allergy-infant","milk-allergy-infant-v2"],validates:["CMP in breast milk","Maternal elimination counseling","Hydrolyzed vs amino acid formula","Baked milk ladder","75% tolerate baked milk by age 1"]},
{id:"PALISADE-2018",title:"AR101 oral immunotherapy for peanut allergy",authors:"PALISADE Group.",journal:"N Engl J Med",year:2018,doi:"10.1056/NEJMoa1812856",pmcid:"PMC7643555",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC7643555/",oa:true,cases:["food-allergy-oit-reaction","food-allergy-oit-reaction-v2","peanut-allergy-anaphylaxis"],validates:["OIT efficacy","Exercise restriction 2h window","OIT = protection, not cure"]}
],
atopicDermatitis:[
{id:"AAD-AD-2023",title:"AAD guidelines for management of atopic dermatitis with topical therapies",authors:"Sidbury R, Alikhan A, Bercovitch L, et al.",journal:"J Am Acad Dermatol",year:2023,doi:"10.1016/j.jaad.2022.12.029",url:"https://www.jaad.org/article/S0190-9622(22)03243-4/fulltext",oa:true,cases:["atopic-dermatitis-severe","atopic-dermatitis-severe-v2","eczema-herpeticum","eczema-herpeticum-v2"],validates:["SCORAD scoring","TCS potency ladder","Wet wrap therapy","Simplified regimens","Eczema herpeticum as emergency"]}
],
rhinitis:[
{id:"ARIA-2020",title:"ARIA guideline 2019: treatment of allergic rhinitis",authors:"Bousquet J, Schunemann HJ, Togias A, et al.",journal:"Allergy",year:2020,doi:"10.1111/all.14049",url:"https://pubmed.ncbi.nlm.nih.gov/31473041/",oa:true,cases:["allergic-rhinitis-uncontrolled","allergic-rhinitis-uncontrolled-v2"],validates:["Step-up pharmacotherapy","INCS + antihistamine combo","SCIT/SLIT for refractory","United airway (rhinitis + asthma)"]},
{id:"AIT-PP-2011",title:"Allergen immunotherapy: practice parameter 3rd update",authors:"Cox L, Nelson H, Lockey R, et al.",journal:"J Allergy Clin Immunol",year:2011,doi:"10.1016/j.jaci.2010.09.034",url:"https://www.jacionline.org/article/S0091-6749(10)01502-0/fulltext",oa:true,cases:["allergic-rhinitis-uncontrolled-v2","insect-sting-anaphylaxis","insect-sting-anaphylaxis-v2","venom-immunotherapy-reaction","venom-immunotherapy-reaction-v2"],validates:["SCIT protocols","Cluster/rush protocols","ACE inhibitors increase VIT reactions","VIT ≥5 years"]}
],
insectAllergy:[
{id:"Insect-PP-2017",title:"Stinging insect hypersensitivity: practice parameter 2016",authors:"Golden DBK, Demain J, Freeman T, et al.",journal:"Ann Allergy Asthma Immunol",year:2017,doi:"10.1016/j.anai.2016.10.031",url:"https://pubmed.ncbi.nlm.nih.gov/28007086/",oa:true,cases:["insect-sting-anaphylaxis","insect-sting-anaphylaxis-v2","venom-immunotherapy-reaction","venom-immunotherapy-reaction-v2"],validates:["60% recurrence without VIT","VIT reduces to <5%","Baseline tryptase screening","Cluster VIT protocol"]}
],
mastCell:[
{id:"MCAS-Consensus-2019",title:"Mast cell activation syndrome: clinicopathological approach",authors:"Weiler CR, Austen KF, Akin C, et al.",journal:"Ann Allergy Asthma Immunol",year:2019,doi:"10.1016/j.anai.2019.09.025",pmcid:"PMC6920833",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC6920833/",oa:true,cases:["mastocytosis","mastocytosis-v2"],validates:["MCAS consensus criteria","Tryptase formula: acute ≥ (1.2 × baseline) + 2","24h urine mediators","KIT D816V for SM vs MCAS","Quadruple therapy"]},
{id:"Valent-MCD-2012",title:"Definitions, criteria and classification of mast cell disorders",authors:"Valent P, Akin C, Arock M, et al.",journal:"J Allergy Clin Immunol",year:2012,doi:"10.1016/j.jaci.2012.09.002",pmcid:"PMC3742415",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3742415/",oa:true,cases:["mastocytosis","mastocytosis-v2"],validates:["SM classification","WHO criteria","KIT D816V","Baseline tryptase >20 suggests SM"]}
],
immunodeficiency:[
{id:"AAAAI-PID-PP-2015",title:"Practice parameter for the diagnosis and management of primary immunodeficiency",authors:"Bonilla FA, Barlan I, Chapel H, et al.",journal:"J Allergy Clin Immunol",year:2015,doi:"10.1016/j.jaci.2015.04.049",pmcid:"PMC4837186",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC4837186/",oa:true,cases:["cvid-presentation","cvid-presentation-v2"],validates:["CVID criteria: low IgG + low IgA/IgM + poor vaccine responses","IgA deficiency → CVID spectrum","IVIG/SCIG replacement","IgA-depleted products","Trough IgG >500"]},
{id:"SCIG-Review-2008",title:"Subcutaneous immunoglobulin replacement: a new paradigm",authors:"Berger M.",journal:"Immunol Allergy Clin North Am",year:2008,doi:"10.1016/j.iac.2008.07.002",pmcid:"PMC3576822",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3576822/",oa:true,cases:["cvid-presentation","cvid-presentation-v2"],validates:["SCIG vs IVIG","Weekly home infusion","Stable IgG levels","Patient preference"]}
],
contactDermatitis:[
{id:"Patch-Testing-PP-2015",title:"Patch testing",authors:"Fonacier L, Bernstein DI, Borish L, et al.",journal:"J Allergy Clin Immunol",year:2015,doi:"10.1016/j.jaci.2015.02.033",url:"https://www.jacionline.org/article/S0091-6749(15)00322-9/fulltext",oa:true,cases:["contact-dermatitis-occupational","contact-dermatitis-occupational-v2"],validates:["Patch test interpretation","PPD as common occupational allergen","PPD-free alternatives for hairstylists","Nitrile vs latex gloves"]}
],
conjunctivitis:[
{id:"VKC-Leonardi-2007",title:"Vernal keratoconjunctivitis: severe allergic eye disease with remodeling",authors:"Leonardi A, De Dominicis C, Motterle L.",journal:"Pediatr Allergy Immunol",year:2007,doi:"10.1111/j.1399-3038.2007.00658.x",url:"https://pubmed.ncbi.nlm.nih.gov/18078420/",oa:false,cases:["allergic-conjunctivitis-severe","allergic-conjunctivitis-severe-v2"],validates:["Giant papillae, shield ulcers, Horner-Trantas dots","Young males, African American/Middle Eastern","Steroid-sparing: tacrolimus/cyclosporine","Shield ulcers → permanent corneal scarring"]}
],
contrastReactions:[
{id:"ACR-Contrast-2024",title:"ACR Manual on Contrast Media",authors:"ACR Committee on Drugs and Contrast Media.",journal:"ACR Manual",year:2024,url:"https://www.acr.org/Clinical-Resources/Contrast-Manual",oa:true,cases:["severe-allergic-reaction-v2"],validates:["Premedication: prednisone -13h/-7h/-1h + diphenhydramine -1h","Anaphylactoid = non-IgE","Reduces recurrence 35% → <1%"]}
]
};
