/* emr-data/manifest.js — EMR Case Manifest
 * Provides window.EMR_MANIFEST used by admissions, ed-3d, night-float, virtual-emr.
 * Each entry is a batch grouped by presentation.
 * Updated: March 2026 — added 29 new cases across neurology, infectious, renal,
 * psychiatric, endocrine, oncology, MSK, cardiology, pulmonary, GI, dermatology,
 * pediatric, obstetric specialties.
 */
var EMR_MANIFEST = window.EMR_MANIFEST || [
  { presentation:"Chest Pain", cases:[
    {id:"stemi-v1",diagnosis:"ST-Elevation MI",category:"cardiology",acuity:1,cc:"Crushing chest pain radiating to left arm \u00D7 1hr",usmle_domain:"EM",usmle_system:"Cardiology",usmle_topic:"Door-to-balloon under 90 min, PCI vs thrombolysis, anticoagulation, right-sided leads"},
    {id:"nstemi-v1",diagnosis:"NSTEMI",category:"cardiology",acuity:2,cc:"Chest pressure and shortness of breath \u00D7 3hrs",usmle_domain:"IM",usmle_system:"Cardiology",usmle_topic:"TIMI/GRACE score, dual antiplatelet loading, early invasive strategy, troponin kinetics"},
    {id:"acute-coronary-syndrome",diagnosis:"Acute Coronary Syndrome",category:"cardiology",acuity:2,cc:"Substernal chest tightness with exertion, worse today",usmle_domain:"IM",usmle_system:"Cardiology",usmle_topic:"ACS spectrum, TIMI score, dual antiplatelet, early invasive strategy"},
        {id:"pe-v2",diagnosis:"Submassive PE with RV Dysfunction — Apixaban Underuse",category:"pulmonary",acuity:1,cc:"Syncope, submassive PE, RV dysfunction — DOAC underuse due to cost",usmle_domain:"EM",usmle_system:"Pulmonary/Cardiology",usmle_topic:"Submassive vs massive PE, PERT activation, CDT vs systemic lysis, avoid fluid loading in RV failure"},
    {id:"pe-v3",diagnosis:"Antiphospholipid Syndrome — Triple Positive",category:"hematologic",acuity:3,cc:"Triple-positive APS — how long to anticoagulate?",usmle_domain:"IM",usmle_system:"Hematology/Rheumatology",usmle_topic:"Triple-positive APS, lifelong warfarin, DOAC contraindicated per TRAPS trial, SLE workup, pregnancy counseling"},
    {id:"pe-v1",diagnosis:"Pulmonary Embolism",category:"pulmonary",acuity:1,cc:"Sudden onset pleuritic chest pain and dyspnea",usmle_domain:"EM",usmle_system:"Cardiology/Pulmonary",usmle_topic:"Wells score, PESI severity, anticoagulation choice, thrombolysis criteria"},
    {id:"pericarditis-v1",diagnosis:"Pericarditis",category:"cardiology",acuity:3,cc:"Sharp chest pain worse when lying flat, better leaning forward",usmle_domain:"IM",usmle_system:"Cardiology",usmle_topic:"Sharp positional chest pain, diffuse ST elevation, colchicine + NSAIDs, AVOID in STEMI"},
    {id:"aortic-dissection-back",diagnosis:"Aortic Dissection",category:"cardiology",acuity:1,cc:"Sudden tearing chest pain radiating to back",usmle_domain:"EM",usmle_system:"Cardiology/Vascular",usmle_topic:"Stanford Type A vs B, BP control, emergent surgery vs medical management"},
    {id:"pneumothorax",diagnosis:"Pneumothorax",category:"pulmonary",acuity:2,cc:"Acute onset right-sided chest pain and difficulty breathing",usmle_domain:"EM",usmle_system:"Pulmonary",usmle_topic:"Primary vs secondary, tension vs spontaneous, needle decompression, chest tube indications"}
  ]},
  { presentation:"Dyspnea", cases:[
    {id:"chf-exacerbation",diagnosis:"CHF Exacerbation",category:"cardiology",acuity:2,cc:"Worsening shortness of breath, can't lie flat, leg swelling \u00D7 3 days",usmle_domain:"IM",usmle_system:"Cardiology",usmle_topic:"Decompensated HF, IV diuresis, BNP, afterload reduction, daily weights"},
    {id:"copd-v1",diagnosis:"COPD Exacerbation",category:"pulmonary",acuity:2,cc:"Worsening dyspnea and productive cough \u00D7 3 days",usmle_domain:"IM",usmle_system:"Pulmonary",usmle_topic:"GOLD staging, SABA + LAMA, systemic steroids, antibiotic criteria in exacerbation"},
    {id:"copd-exacerbation-niv",diagnosis:"Severe COPD Exacerbation — Acute Hypercapnic Respiratory Failure — BiPAP",category:"pulmonary",acuity:2,cc:"77M GOLD IV COPD DNI, pH 7.29 pCO2 72, SpO2 84%, BiPAP initiated",usmle_domain:"IM",usmle_system:"Pulmonary",usmle_topic:"BiPAP indications pH below 7.35, O2 target 88-92%, Haldane effect, DNI/DNR navigation"},
    {id:"asthma-exacerbation",diagnosis:"Asthma Exacerbation",category:"pulmonary",acuity:2,cc:"Wheezing and difficulty breathing, inhaler not helping",usmle_domain:"IM",usmle_system:"Pulmonary",usmle_topic:"Peak flow, SABA + SAMA, Mg sulfate, heliox, intubation decision"},
    {id:"pneumonia",diagnosis:"Community-Acquired Pneumonia",category:"infectious",acuity:3,cc:"Fever, cough with yellow sputum, shortness of breath \u00D7 4 days",usmle_domain:"IM",usmle_system:"Pulmonary/ID",usmle_topic:"CAP pathogens, CURB-65 scoring, empiric antibiotics, inpatient vs outpatient"},
    {id:"community-acquired-pneumonia",diagnosis:"Community-Acquired Pneumonia — S. pneumoniae — CURB-65 3",category:"infectious",acuity:2,cc:"74F COPD, 5-day fever + productive cough, SpO2 88%, CURB-65 score 3",usmle_domain:"IM",usmle_system:"Pulmonary/ID",usmle_topic:"CURB-65 scoring, O2 target 88-92% in COPD, PCV20 gap, 6-8wk follow-up CXR"},
    {id:"massive-pe-with-rv-failure",diagnosis:"Massive PE with RV Failure",category:"pulmonary",acuity:1,cc:"Sudden severe dyspnea, near-syncope, cannot catch breath",usmle_domain:"EM",usmle_system:"Cardiology/Pulmonary",usmle_topic:"Massive PE, systemic thrombolysis, catheter-directed therapy, RV strain on echo"},
    {id:"vocal-cord-dysfunction",diagnosis:"Vocal Cord Dysfunction (PVFM)",category:"pulmonary",acuity:3,cc:"Episodic inspiratory stridor and throat tightness — misdiagnosed as asthma for 2 years",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"PVFM/VCD, inspiratory stridor, misdiagnosed as asthma, laryngoscopy, speech therapy"}
  ]},
  { presentation:"Altered Mental Status", cases:[
        {id:"dka-v2",diagnosis:"Cerebral Edema Complicating Pediatric DKA",category:"endocrine",acuity:1,cc:"Neurological deterioration during DKA treatment — GCS drop, Cushing triad, papilledema",usmle_domain:"EM",usmle_system:"Endocrinology/Neurology",usmle_topic:"DKA cerebral edema, mannitol STAT, slow fluids, never bolus during neurological decline"},
    {id:"dka-v3",diagnosis:"Recurrent DKA — Insulin Access Barrier",category:"endocrine",acuity:3,cc:"Third DKA in 4 months — CGM denied by insurance, insulin rationing",usmle_domain:"IM",usmle_system:"Endocrinology",usmle_topic:"SDOH in T1DM, CGM prior auth, insulin assistance programs, sick day rules education"},
    {id:"dka-v1",diagnosis:"Diabetic Ketoacidosis",category:"endocrine",acuity:1,cc:"Nausea, vomiting, abdominal pain, increasingly confused \u00D7 2 days",usmle_domain:"IM",usmle_system:"Endocrinology",usmle_topic:"Anion gap, insulin drip protocol, potassium replacement before insulin, bicarbonate indications"},
        {id:"stroke-v2",diagnosis:"Hemorrhagic Transformation Post-tPA (PH2)",category:"neurology",acuity:1,cc:"Worsening neurological status 6 hours after tPA — NIHSS 22, Cushing triad",usmle_domain:"EM",usmle_system:"Neurology",usmle_topic:"PH2 hemorrhagic conversion, mannitol, BP control after tPA, no anticoagulation"},
    {id:"stroke-v3",diagnosis:"Post-Stroke: Aspiration Pneumonia + New-Onset AF",category:"neurology",acuity:2,cc:"Day 5 post-stroke — aspiration event and paroxysmal AF with anticoagulation dilemma",usmle_domain:"IM",usmle_system:"Neurology",usmle_topic:"Post-stroke AF anticoagulation timing after PH2, aspiration pneumonia, stroke rehab disposition"},
    {id:"stroke-v1",diagnosis:"Acute Ischemic Stroke",category:"neurology",acuity:1,cc:"Sudden left-sided weakness and slurred speech \u00D7 45min",usmle_domain:"EM",usmle_system:"Neurology",usmle_topic:"NIHSS, tPA window, BP management pre/post tPA, swallow screen, DVT prophylaxis"},
    {id:"meningitis-v1",diagnosis:"Bacterial Meningitis",category:"infectious",acuity:1,cc:"Severe headache, neck stiffness, fever, photophobia",usmle_domain:"EM",usmle_system:"Neurology/ID",usmle_topic:"LP before CT if no focal deficits, empiric ceftriaxone + dexamethasone, blood cultures first"},
    {id:"status-epilepticus",diagnosis:"Status Epilepticus",category:"neurology",acuity:1,cc:"Witnessed seizure, not stopping, ongoing convulsions",usmle_domain:"EM",usmle_system:"Neurology",usmle_topic:"Benzodiazepine first-line, levetiracetam or valproate second, airway management, EEG"},
    {id:"severe-hyponatremia",diagnosis:"Severe Hyponatremia",category:"renal",acuity:2,cc:"Confusion, lethargy, found acting strange by family",usmle_domain:"IM",usmle_system:"Renal",usmle_topic:"Hypo-osmolar hyponatremia, SIADH vs hypovolemic, 3% saline, ODS risk with rapid correction"},
    {id:"alcohol-withdrawal",diagnosis:"Alcohol Withdrawal — CIWA 22 — DTs Prevention",category:"psychiatric",acuity:2,cc:"54M daily fifth x6yr, LDA 18h, tremor, diaphoresis, formication, prior withdrawal seizure",usmle_domain:"PSY",usmle_system:"Psychiatry",usmle_topic:"CIWA-Ar scoring, thiamine BEFORE glucose, symptom-triggered protocol, DTs timeline"},
    {id:"delirium-elderly",diagnosis:"Post-Operative Delirium — Hyperactive — Elderly",category:"geriatric",acuity:2,cc:"85F post-op day 1 hip replacement, acute confusion, CAM positive, multiple precipitants",usmle_domain:"IM",usmle_system:"Geriatrics",usmle_topic:"CAM criteria, FIND ME precipitants, STOP diphenhydramine Beers, non-pharm management"}
  ]},
  { presentation:"Abdominal Pain", cases:[
    {id:"appendicitis-v1",diagnosis:"Acute Appendicitis",category:"surgery",acuity:2,cc:"RLQ abdominal pain, nausea, low-grade fever \u00D7 18hrs",usmle_domain:"SUR",usmle_system:"GI/Surgery",usmle_topic:"Alvarado score, CT vs ultrasound, laparoscopic appendectomy, perforation management"},
    {id:"acute-pancreatitis",diagnosis:"Acute Pancreatitis",category:"gi",acuity:2,cc:"Severe epigastric pain radiating to back after drinking",usmle_domain:"IM",usmle_system:"GI",usmle_topic:"Revised Atlanta, BISAP score, IVF resuscitation, no routine antibiotics"},
    {id:"acute-cholecystitis",diagnosis:"Acute Cholecystitis",category:"gi",acuity:3,cc:"RUQ pain after eating, worse with fatty food, nausea",usmle_domain:"SUR",usmle_system:"GI/Surgery",usmle_topic:"Tokyo guidelines, laparoscopic cholecystectomy timing, Murphy sign"},
    {id:"sbo-strangulation",diagnosis:"SBO with Strangulation",category:"surgery",acuity:1,cc:"Abdominal distension, bilious vomiting, severe crampy pain",usmle_domain:"SUR",usmle_system:"GI/Surgery",usmle_topic:"Closed-loop obstruction, peritoneal signs mean OR, NGT decompression, strangulation indicators"},
    {id:"mesenteric-ischemia",diagnosis:"Mesenteric Ischemia",category:"surgery",acuity:1,cc:"Severe abdominal pain out of proportion to exam, bloody stool",usmle_domain:"SUR",usmle_system:"GI/Surgery",usmle_topic:"Pain out of proportion to exam, CTA mesenteric vessels, embolectomy vs bypass, bowel viability"},
    {id:"perforated-peptic-ulcer",diagnosis:"Perforated Peptic Ulcer",category:"surgery",acuity:1,cc:"Sudden onset severe epigastric pain, rigid abdomen",usmle_domain:"SUR",usmle_system:"GI/Surgery",usmle_topic:"Free air on imaging, emergent laparotomy, H. pylori testing, PPI + triple therapy"},
    {id:"upper-gi-bleed",diagnosis:"Upper GI Bleed — Duodenal Ulcer — H. pylori Positive",category:"gi",acuity:1,cc:"63M hematemesis + melena, NSAID use + heavy ETOH, GBS 12, Forrest Ia — endoscopic hemostasis",usmle_domain:"IM",usmle_system:"GI",usmle_topic:"Glasgow-Blatchford score, octreotide for suspected varices, Forrest Ia rebleed risk, H. pylori eradication"},
    {id:"ibs-management",diagnosis:"Irritable Bowel Syndrome — Mixed Type — Rome IV Criteria",category:"gi",acuity:3,cc:"35F 14-month abdominal pain relieved by defecation, alternating bowel habits, normal colonoscopy",usmle_domain:"IM",usmle_system:"GI",usmle_topic:"Rome IV criteria, red flags, low FODMAP, amitriptyline neuromodulator, no opioids"}
  ]},
  { presentation:"Neurologic Emergency", cases:[
    {id:"sah-v1",diagnosis:"Subarachnoid Hemorrhage",category:"neurology",acuity:1,cc:"Sudden worst headache of my life, neck stiffness",usmle_domain:"EM",usmle_system:"Neurology",usmle_topic:"Thunderclap headache, LP xanthochromia, CTA, aneurysm coiling vs clipping"},
    {id:"acute-ischemic-stroke-tpa",diagnosis:"Acute Ischemic Stroke — LVO — tPA + Thrombectomy",category:"neurology",acuity:1,cc:"75F AF on apixaban, sudden aphasia + right hemiplegia, NIHSS 18",usmle_domain:"EM",usmle_system:"Neurology",usmle_topic:"tPA eligibility, anti-Xa threshold for DOACs, LVO thrombectomy, HI-1 post-procedure"},
    {id:"guillain-barre",diagnosis:"Guillain-Barré Syndrome",category:"neurology",acuity:2,cc:"37F progressive ascending weakness x10 days, areflexia, post-Campylobacter",usmle_domain:"IM",usmle_system:"Neurology",usmle_topic:"Rule of 20s for intubation, NO succinylcholine use rocuronium, IVIG vs PLEX, autonomic instability"},
    {id:"new-onset-seizure",diagnosis:"New-Onset Seizure — CNS Toxoplasmosis (HIV)",category:"neurology",acuity:2,cc:"40F HIV+ CD4 68, new tonic-clonic seizure, 3-week headache, ring-enhancing lesion",usmle_domain:"IM",usmle_system:"Neurology",usmle_topic:"Organic workup first, CNS toxoplasmosis in HIV CD4 68, ring-enhancing lesion, anti-NMDA Ab"},
    {id:"hypertensive-emergency",diagnosis:"Hypertensive Emergency with End-Organ Damage",category:"neurology",acuity:2,cc:"57M BP 226/138, severe headache, blurred vision, papilledema",usmle_domain:"IM",usmle_system:"Neurology/Cardiovascular",usmle_topic:"MAP reduction targets, PRES on MRI, nicardipine/labetalol, overcorrection causes stroke"},
    {id:"new-seizure-mass",diagnosis:"New-Onset Seizure (Brain Mass)",category:"neurology",acuity:2,cc:"New-onset seizure, no prior history, persistent headache",usmle_domain:"IM",usmle_system:"Neurology/Oncology",usmle_topic:"New seizure with intracranial mass, metastatic vs primary, dexamethasone, levetiracetam"},
    {id:"cauda-equina",diagnosis:"Cauda Equina Syndrome",category:"neurology",acuity:2,cc:"Severe low back pain, bilateral leg weakness, trouble urinating",usmle_domain:"SUR",usmle_system:"Neurology/Spine",usmle_topic:"Saddle anesthesia, bowel/bladder dysfunction, emergency MRI, surgical decompression"}
  ]},
  { presentation:"Headache", cases:[
    {id:"migraine",diagnosis:"Migraine",category:"neurology",acuity:4,cc:"Severe throbbing headache with aura, nausea, photophobia \u00D7 6hrs",usmle_domain:"IM",usmle_system:"Neurology",usmle_topic:"ICHD-3 criteria, abortive vs preventive therapy, triptan use"},
    {id:"migraine-management",diagnosis:"Migraine with Aura — Preventive Therapy — OCP Contraindicated",category:"neurology",acuity:3,cc:"37F migraine with aura 3x/week, MIDAS 22, daily NSAIDs — topiramate + sumatriptan + stop OCP",usmle_domain:"IM",usmle_system:"Neurology",usmle_topic:"ICHD-3, OCP contraindicated with aura stroke risk, status migrainosus IV protocol, MOH prevention"}
  ]},
  { presentation:"Infectious Disease", cases:[
    {id:"sepsisseptic-shock",diagnosis:"Sepsis/Septic Shock",category:"infectious",acuity:1,cc:"High fever, chills, confusion, feeling very ill \u00D7 1 day",usmle_domain:"EM",usmle_system:"ID/Critical Care",usmle_topic:"Sepsis-3, qSOFA, hour-1 bundle, vasopressors, source control"},
    {id:"infective-endocarditis",diagnosis:"Infective Endocarditis — Tricuspid Valve — MSSA — IVDU",category:"infectious",acuity:2,cc:"31M IVDU, 3-week fever, new murmur, splinter hemorrhages, septic pulmonary emboli",usmle_domain:"IM",usmle_system:"Cardiology/ID",usmle_topic:"Modified Duke criteria, nafcillin over vancomycin for MSSA, MOUD during hospitalization"},
    {id:"pyelonephritis-sepsis",diagnosis:"Urosepsis — Pyelonephritis — E. coli Bacteremia — Antibiotic De-escalation",category:"infectious",acuity:2,cc:"70F DM2, sulfa + PCN allergy — urosepsis qSOFA 2 — ceftriaxone to PO ciprofloxacin",usmle_domain:"IM",usmle_system:"Renal/ID",usmle_topic:"Sepsis-3 criteria, PCN allergy cross-reactivity under 2%, fluoroquinolone resistance, de-escalation"},
    {id:"pyelonephritis-urosepsis",diagnosis:"Pyelonephritis/Urosepsis",category:"infectious",acuity:2,cc:"Flank pain, fever, burning with urination, rigors",usmle_domain:"IM",usmle_system:"Renal/ID",usmle_topic:"Urosepsis management, blood cultures before antibiotics, source control"},
    {id:"septic-shock-urosepsis",diagnosis:"Septic Shock (Urosepsis)",category:"infectious",acuity:1,cc:"High fever, confusion, low blood pressure, urinary symptoms",usmle_domain:"EM",usmle_system:"ID/Critical Care",usmle_topic:"Septic shock from urinary source, vasopressor initiation, blood cultures before antibiotics"},
    {id:"nec-fasciitis",diagnosis:"Necrotizing Fasciitis",category:"infectious",acuity:1,cc:"Rapidly spreading painful red skin, blistering, high fever, toxic-appearing",usmle_domain:"SUR",usmle_system:"Surgery/ID",usmle_topic:"LRINEC score, Type I vs II, broad-spectrum antibiotics plus emergent surgical debridement"},
    {id:"fournier-gangrene",diagnosis:"Fournier Gangrene",category:"infectious",acuity:1,cc:"Severe perineal pain, swelling, fever, foul-smelling drainage",usmle_domain:"SUR",usmle_system:"Urology/Surgery",usmle_topic:"Perineal necrotizing fasciitis, LRINEC score, broad-spectrum antibiotics, surgical debridement"}
  ]},
  { presentation:"Fever", cases:[
    {id:"neutropenic-fever",diagnosis:"Neutropenic Fever",category:"hematology",acuity:1,cc:"Fever and chills on chemotherapy, feeling weak",usmle_domain:"IM",usmle_system:"Hematology/Oncology",usmle_topic:"Febrile neutropenia, ANC below 500, empiric broad-spectrum antibiotics, risk stratification"},
    {id:"febrile-neutropenia",diagnosis:"Febrile Neutropenia — E. coli Bacteremia — Breast Cancer",category:"hematology",acuity:2,cc:"56F on dose-dense AC chemo day 10, fever 38.8°C, ANC 180 — door-to-abx <60 min",usmle_domain:"IM",usmle_system:"Hematology/Oncology",usmle_topic:"MASCC risk score, door-to-antibiotic 60 min, cefepime empiric, vancomycin NOT routine"}
  ]},
  { presentation:"Syncope", cases:[
    {id:"cardiac-syncope",diagnosis:"Cardiac Syncope",category:"cardiology",acuity:2,cc:"Passed out without warning while sitting, palpitations before",usmle_domain:"IM",usmle_system:"Cardiology",usmle_topic:"High-risk features, San Francisco Syncope Rule, Holter vs loop recorder, ICD criteria"},
    {id:"vasovagal-syncope",diagnosis:"Vasovagal Syncope",category:"cardiology",acuity:4,cc:"Felt lightheaded then passed out briefly, came right back",usmle_domain:"IM",usmle_system:"Cardiology",usmle_topic:"Prodrome recognition, tilt table test, salt plus fluid loading, fludrocortisone"},
    {id:"pulmonary-embolism-syncope",diagnosis:"PE with Syncope",category:"pulmonary",acuity:1,cc:"Sudden collapse, brief LOC, now short of breath and chest pain",usmle_domain:"EM",usmle_system:"Cardiology/Pulmonary",usmle_topic:"PE presenting as syncope, massive PE with hemodynamic compromise, thrombolysis"}
  ]},
  { presentation:"Cardiac Emergency", cases:[
    {id:"cardiac-tamponade",diagnosis:"Cardiac Tamponade",category:"cardiac",acuity:1,cc:"Chest pain, shortness of breath, muffled heart sounds, hypotension",usmle_domain:"EM",usmle_system:"Cardiology",usmle_topic:"Beck's triad, pulsus paradoxus, pericardiocentesis, electrical alternans"},
    {id:"complete-heart-block",diagnosis:"Complete Heart Block",category:"cardiac",acuity:2,cc:"Dizzy spells, near-syncope, heart rate in the 30s",usmle_domain:"EM",usmle_system:"Cardiology",usmle_topic:"Atropine, transcutaneous pacing, transvenous pacing, permanent pacemaker indications"},
    {id:"vt-syncope",diagnosis:"Ventricular Tachycardia with Syncope",category:"cardiology",acuity:2,cc:"Passed out at home, palpitations, chest discomfort",usmle_domain:"IM",usmle_system:"Cardiology",usmle_topic:"VT vs SVT with aberrancy, Brugada criteria, AICD indications, antiarrhythmic selection"},
    {id:"chf-v1",diagnosis:"Acute Decompensated Heart Failure",category:"cardiology",acuity:2,cc:"Can't breathe lying down, legs very swollen, gained 15 lbs in a week",usmle_domain:"IM",usmle_system:"Cardiology",usmle_topic:"Acute decompensated heart failure, diuresis, hemodynamic profiling"},
    {id:"new-onset-atrial-fibrillation",diagnosis:"New-Onset Atrial Fibrillation — Cardioversion — Anticoagulation",category:"cardiology",acuity:2,cc:"65M sudden palpitations + dyspnea x4h, HR 142 irregular, CHA2DS2-VASc 2",usmle_domain:"IM",usmle_system:"Cardiology",usmle_topic:"CHA2DS2-VASc, cardioversion under 12h without anticoagulation bridge, atrial stunning post-cardioversion"},
    {id:"heart-failure-hfpef",diagnosis:"Acute Decompensated HFpEF — Empagliflozin Initiation",category:"cardiology",acuity:2,cc:"77F HTN/DM2/AF, orthopnea + leg edema, BNP 820, EF 62% — IV diuresis + SGLT2i",usmle_domain:"IM",usmle_system:"Cardiology",usmle_topic:"HFpEF vs HFrEF treatment differences, EMPEROR-Preserved SGLT2i, IV over PO diuretics"}
  ]},
  { presentation:"Toxicology", cases:[
    {id:"apap-overdose",diagnosis:"Acetaminophen Overdose",category:"toxicology",acuity:2,cc:"Took a bottle of Tylenol, nausea, RUQ pain",usmle_domain:"EM",usmle_system:"Toxicology",usmle_topic:"Rumack-Matthew nomogram, NAC protocol, hepatotoxicity staging"},
    {id:"serotonin-syndrome",diagnosis:"Serotonin Syndrome",category:"toxicology",acuity:2,cc:"Agitation, tremor, diaphoresis, recently started new antidepressant",usmle_domain:"EM",usmle_system:"Toxicology/Psychiatry",usmle_topic:"Hunter criteria vs NMS, cyproheptadine, benzodiazepines, discontinue serotonergic agents"},
    {id:"salicylate-toxicity",diagnosis:"Salicylate Toxicity",category:"toxicology",acuity:1,cc:"Tinnitus, rapid breathing, confusion after taking many aspirin",usmle_domain:"EM",usmle_system:"Toxicology",usmle_topic:"Mixed acid-base disorder, urinary alkalinization, hemodialysis criteria"}
  ]},
  { presentation:"Hematologic", cases:[
    {id:"ttp",diagnosis:"TTP",category:"hematology",acuity:1,cc:"Easy bruising, confusion, petechiae, dark urine",usmle_domain:"IM",usmle_system:"Hematology",usmle_topic:"Pentad, ADAMTS13, plasmapheresis, AVOID platelet transfusion, rituximab for refractory"},
    {id:"sle-flare-with-cytopenias",diagnosis:"SLE Flare with Cytopenias",category:"hematology",acuity:2,cc:"Joint pain, fatigue, rash, low blood counts found on labs",usmle_domain:"IM",usmle_system:"Musculoskeletal/Renal",usmle_topic:"ACR/EULAR criteria, anti-dsDNA, hydroxychloroquine, lupus nephritis biopsy, SLEDAI"},
    {id:"autoimmune-hemolytic-anemia",diagnosis:"Autoimmune Hemolytic Anemia",category:"hematology",acuity:2,cc:"Fatigue, jaundice, dark urine, feeling lightheaded",usmle_domain:"IM",usmle_system:"Hematology",usmle_topic:"Warm vs cold AIHA, DAT, steroids, rituximab, transfusion risks"},
    {id:"dic-massive-transfusion",diagnosis:"DIC with Massive Hemorrhage",category:"hematology",acuity:1,cc:"Bleeding from multiple sites, oozing from IV sites, recent surgery",usmle_domain:"IM",usmle_system:"Hematology",usmle_topic:"DIC vs TTP, massive transfusion protocol, 1:1:1 ratio, cryoprecipitate for fibrinogen"}
  ]},
  { presentation:"Oncology", cases:[
    {id:"lung-cancer-staging",diagnosis:"Non-Small Cell Lung Cancer — Squamous Cell — Stage IIIA Staging Workup",category:"hematology",acuity:3,cc:"74M 55 pack-years, 4-month cough + 18lb weight loss, right hilar mass, EBUS-confirmed N2 disease",usmle_domain:"IM",usmle_system:"Hematology/Oncology",usmle_topic:"TNM staging, PET/CT, EBUS tissue, molecular profiling EGFR/ALK/PD-L1, PACIFIC trial"}
  ]},
  { presentation:"Renal/Electrolyte", cases:[
    {id:"hyperkalemia-cardiac",diagnosis:"Hyperkalemia with Cardiac Changes",category:"renal",acuity:1,cc:"Generalized weakness, missed dialysis \u00D7 2 sessions, palpitations",usmle_domain:"IM",usmle_system:"Renal/Cardiology",usmle_topic:"EKG changes, calcium gluconate stabilizes membrane, insulin plus glucose, kayexalate vs patiromer"},
    {id:"renal-colic",diagnosis:"Renal Colic",category:"renal",acuity:3,cc:"Severe left flank pain, hematuria, cannot sit still",usmle_domain:"EM",usmle_system:"Urology",usmle_topic:"CT KUB vs ultrasound, tamsulosin medical expulsive therapy, urology referral criteria"},
    {id:"aki-differential",diagnosis:"Acute Kidney Injury — Prerenal vs NSAID-Induced ATN",category:"renal",acuity:2,cc:"69M Cr 4.2 from 0.9 after gastroenteritis + NSAID use, K+ 5.9, oliguria",usmle_domain:"IM",usmle_system:"Renal",usmle_topic:"FENa interpretation, NSAID nephrotoxicity, medications to hold in AKI"},
    {id:"rhabdomyolysis",diagnosis:"Rhabdomyolysis — Statin-Induced + Exertional",category:"renal",acuity:2,cc:"47M on rosuvastatin, boot camp exercise, CK 48,000, cola-colored urine, AKI",usmle_domain:"IM",usmle_system:"Renal/Musculoskeletal",usmle_topic:"CK threshold, IVF target UO 200-300 mL/hr, statin myopathy dose-dependence, pravastatin at discharge"}
  ]},
  { presentation:"Endocrine", cases:[
    {id:"thyroid-storm",diagnosis:"Thyroid Storm",category:"endocrine",acuity:1,cc:"High fever, racing heart, agitation, tremor, known thyroid disease",usmle_domain:"EM",usmle_system:"Endocrinology",usmle_topic:"Burch-Wartofsky score, PTU before iodine, SSKI, beta-blockade, cooling, steroids"},
    {id:"adrenal-crisis",diagnosis:"Adrenal Crisis",category:"endocrine",acuity:1,cc:"Severe weakness, hypotension, abdominal pain, on chronic steroids that were stopped",usmle_domain:"EM",usmle_system:"Endocrinology",usmle_topic:"Hydrocortisone 100mg IV, stress dosing, mineralocorticoid replacement"},
    {id:"myxedema-coma",diagnosis:"Myxedema Coma",category:"endocrine",acuity:1,cc:"Found lethargic, hypothermic, bradycardic, known hypothyroidism",usmle_domain:"EM",usmle_system:"Endocrinology",usmle_topic:"IV T4 + T3, warming, hydrocortisone empiric, ICU monitoring, bradycardia management"},
    {id:"hypercalcemia",diagnosis:"Hypercalcemia of Malignancy — PTHrP-Mediated",category:"endocrine",acuity:2,cc:"72M stage IV squamous cell lung cancer, confusion, Ca 14.2, polyuria",usmle_domain:"IM",usmle_system:"Endocrinology",usmle_topic:"Corrected calcium, PTH vs PTHrP differential, IVF cornerstone, zoledronic acid, NOT furosemide first"},
    {id:"inpatient-diabetes-management",diagnosis:"Inpatient Hyperglycemia — Basal-Bolus Insulin Initiation",category:"endocrine",acuity:3,cc:"62F T2DM admitted for CAP, BG 382, oral agents held, needs insulin regimen",usmle_domain:"IM",usmle_system:"Endocrinology",usmle_topic:"NICE-SUGAR target 140-180, basal-bolus over sliding scale, hold metformin/sulfonylureas"},
    {id:"type2-diabetes-outpatient",diagnosis:"Type 2 Diabetes — Outpatient Optimization — Semaglutide",category:"endocrine",acuity:4,cc:"57F T2DM HbA1c 8.8%, obesity BMI 38, ASCVD risk 22%, GLP-1 initiation",usmle_domain:"FAM",usmle_system:"Endocrinology",usmle_topic:"SUSTAIN-6 CV benefit of semaglutide, ASCVD risk, statin missed, SDOH barriers addressed"}
  ]},
  { presentation:"Psychiatric / Behavioral", cases:[
    {id:"nms",diagnosis:"Neuroleptic Malignant Syndrome",category:"psychiatric",acuity:2,cc:"High fever, severe muscle rigidity, confusion, on antipsychotic",usmle_domain:"PSY",usmle_system:"Psychiatry",usmle_topic:"NMS vs serotonin syndrome, STOP antipsychotic, dantrolene + bromocriptine, rhabdo risk"},
    {id:"acute-psychosis",diagnosis:"First-Episode Psychosis — Schizophrenia",category:"psychiatric",acuity:2,cc:"24M paranoid delusions, auditory hallucinations, 6-month prodrome, HIV negative, anti-NMDA negative",usmle_domain:"PSY",usmle_system:"Psychiatry",usmle_topic:"First-episode psychosis, organic workup, risperidone, anti-NMDA exclusion, EPI program"}
  ]},
  { presentation:"Musculoskeletal Emergency", cases:[
    {id:"septic-arthritis",diagnosis:"Septic Arthritis — Right Knee — MSSA — with Gout",category:"musculoskeletal",acuity:2,cc:"63M gout + DM2, acute monoarticular knee swelling, fever 38.8°C, post-cortisone injection",usmle_domain:"IM",usmle_system:"Musculoskeletal",usmle_topic:"Crystals do not exclude infection, synovial WBC above 50k, nafcillin over vancomycin for MSSA"},
    {id:"compartment-syndrome",diagnosis:"Acute Compartment Syndrome",category:"musculoskeletal",acuity:2,cc:"Severe leg pain after injury, pain with passive stretch, tense swelling",usmle_domain:"SUR",usmle_system:"Musculoskeletal/Surgery",usmle_topic:"Compartment pressure measurement, 4-compartment fasciotomy, CK monitoring"}
  ]},
  { presentation:"Musculoskeletal / Clinic", cases:[
    {id:"rheumatoid-arthritis-new",diagnosis:"Rheumatoid Arthritis — New Diagnosis — Methotrexate Initiation",category:"musculoskeletal",acuity:3,cc:"47F bilateral symmetric polyarthritis MCPs/wrists, morning stiffness >1h, anti-CCP 182",usmle_domain:"IM",usmle_system:"Musculoskeletal",usmle_topic:"2010 ACR criteria, anti-CCP significance, MTX weekly not daily, folic acid, treat-to-target"}
  ]},
  { presentation:"Dermatology", cases:[
    {id:"acne-management",diagnosis:"Moderate-Severe Acne — Combination Therapy + Isotretinoin Referral",category:"dermatology",acuity:4,cc:"22F OTC failure, PIH on skin of color, early scarring — doxycycline + tretinoin + azelaic acid",usmle_domain:"FAM",usmle_system:"Dermatology",usmle_topic:"Treatment ladder, antibiotic stewardship, retinoid counseling, PIH in skin of color"},
    {id:"psoriasis-moderate-severe",diagnosis:"Psoriasis — Moderate-Severe — Biologic Initiation (Ixekizumab)",category:"dermatology",acuity:3,cc:"54M plaque psoriasis PASI 18.6 + psoriatic arthritis, methotrexate failure — IL-17A inhibitor",usmle_domain:"FAM",usmle_system:"Dermatology",usmle_topic:"PASI scoring, biologic selection anti-TNF IL-17 IL-23, safety lab monitoring"}
  ]},
  { presentation:"Allergic/Immunologic", cases:[
    {id:"anaphylaxis",diagnosis:"Anaphylaxis",category:"allergy",acuity:1,cc:"Lip swelling, hives, throat tightness after eating",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"Epinephrine IM first-line, biphasic reaction, observation period, auto-injector Rx"},
    {id:"severe-allergic-reaction",diagnosis:"Severe Allergic Reaction",category:"allergy",acuity:2,cc:"Widespread hives, facial swelling after taking medication",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"Grading anaphylaxis severity, epinephrine dosing, adjuncts after epinephrine"},
    {id:"ace-angioedema",diagnosis:"ACE Inhibitor Angioedema",category:"allergy",acuity:2,cc:"Tongue and lip swelling, difficulty swallowing, on lisinopril",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"ACE inhibitor angioedema, bradykinin mechanism, switch to ARB"},
    {id:"hereditary-angioedema",diagnosis:"Hereditary Angioedema",category:"allergy",acuity:2,cc:"Recurrent facial swelling and severe abdominal pain, family history of similar episodes",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"C1 esterase inhibitor deficiency, icatibant/C1-INH concentrate, AVOID ACE inhibitors"},
    {id:"allergic-angioedema",diagnosis:"Allergic Angioedema",category:"allergy",acuity:2,cc:"Acute facial and lip swelling after new medication",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"IgE-mediated angioedema, epinephrine, airway management"},
    {id:"idiopathic-angioedema",diagnosis:"Idiopathic Angioedema",category:"allergy",acuity:3,cc:"Recurrent episodes of hand and facial swelling, no clear trigger",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Idiopathic histaminergic angioedema, antihistamine trial, rule out HAE, complement levels"},
    {id:"acquired-c1esterase-inhibitor-deficiency",diagnosis:"Acquired C1-INH Deficiency",category:"allergy",acuity:2,cc:"Recurrent facial swelling and abdominal pain, not responding to antihistamines",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Acquired angioedema, C1-INH deficiency, lymphoproliferative workup"},
    {id:"abpa-aspergillus",diagnosis:"ABPA (Allergic Bronchopulmonary Aspergillosis)",category:"allergy",acuity:3,cc:"Refractory asthma with recurrent pulmonary infiltrates and peripheral eosinophilia",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"ABPA staging, total IgE, itraconazole, prednisolone"},
    {id:"severe-asthma-biologics",diagnosis:"Severe Eosinophilic Asthma — Biologic Selection",category:"allergy",acuity:3,cc:"4th asthma exacerbation in 12 months despite Step 4 therapy — AERD + CRSwNP + eosinophilia",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"T2 vs non-T2 severe asthma, dupilumab/mepolizumab/benralizumab, FeNO and eosinophils"},
    {id:"occupational-asthma-isocyanate",diagnosis:"Isocyanate Occupational Asthma",category:"allergy",acuity:2,cc:"Work-related wheeze and dyspnea improving on weekends — automotive spray painter",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Serial PEF monitoring, specific inhalation challenge, removal from exposure, compensation"},
    {id:"inducible-urticaria",diagnosis:"Cold-Induced Urticaria",category:"allergy",acuity:3,cc:"Hives and swelling triggered by cold water exposure — nearly drowned",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Dermographism, cold urticaria, solar urticaria, threshold testing, trigger avoidance"},
    {id:"crswNP-biologics",diagnosis:"Severe CRSwNP + AERD — Dupilumab",category:"allergy",acuity:3,cc:"Complete anosmia × 2 years, FESS × 2 failures, severe nasal polyposis with NSAID hypersensitivity",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Type 2 CRS, dupilumab approval, endoscopic sinus surgery candidacy, nasal polyp grading"},
    {id:"allergic-rhinitis-immunotherapy",diagnosis:"Allergic Rhinitis — Allergen Immunotherapy (SCIT)",category:"allergy",acuity:4,cc:"Perennial nasal congestion, sneezing, itchy eyes — dust mite + grass + mold sensitized, SCIT initiation with systemic reaction management",usmle_domain:"FAM",usmle_system:"Allergy/Immunology",usmle_topic:"SCIT build-up vs maintenance, systemic reaction management, SLIT comparison"},
    {id:"hypersensitivity-pneumonitis",diagnosis:"Chronic Fibrotic Hypersensitivity Pneumonitis",category:"allergy",acuity:3,cc:"Progressive dyspnea 14 months, dry cough, weight loss — lifelong bird breeder × 25 years",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"HP vs IPF, antigen exposure history, BAL lymphocytosis, antigen avoidance is key"},
    {id:"hypereosinophilic-syndrome",diagnosis:"Hypereosinophilic Syndrome — FIP1L1-PDGFRA Myeloproliferative",category:"allergy",acuity:2,cc:"Persistent eosinophilia 4,800 cells/µL on routine CBC — fatigue, borderline troponin elevation",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"HES diagnostic criteria, FIP1L1-PDGFRA, imatinib for myeloid HES, organ damage assessment"}
  ]},
  { presentation:"Skin/Drug Reactions", cases:[
    {id:"sjs-ten",diagnosis:"SJS/TEN",category:"allergy",acuity:1,cc:"Widespread skin blistering, painful rash, fever after starting new medication",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"SCORTEN score, offending drug withdrawal, wound care, cyclosporine vs IVIG vs TNF-alpha inhibitors"},
    {id:"sjsten-overlap",diagnosis:"SJS/TEN Overlap",category:"allergy",acuity:1,cc:"Mucosal erosions, skin sloughing, high fever after antibiotic",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"SJS-TEN overlap 10-30% BSA, SCORTEN, ICU burn-unit care"},
    {id:"dress-syndrome",diagnosis:"DRESS Syndrome",category:"allergy",acuity:2,cc:"Fever, diffuse rash, facial swelling 3 weeks after starting new medication",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"DRESS/DiHS, RegiSCAR score, offending drug withdrawal, systemic steroids"},
    {id:"erythema-multiforme-major",diagnosis:"Erythema Multiforme Major",category:"allergy",acuity:3,cc:"Target-shaped skin lesions, mouth sores, painful rash",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"EM major vs SJS, target lesions, HSV trigger, acyclovir suppression"}
  ]},
  // ── Allergy Curriculum Expansion ──
  { presentation:"Urticaria", cases:[
    {id:"acute-urticaria",diagnosis:"Acute Urticaria",category:"allergy",acuity:3,setting:"ed",allergySubtype:"urticaria",allSettings:true,cc:"Sudden onset hives all over body, itching \u00D7 4hrs",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Acute urticaria triggers, antihistamines, when to use epinephrine"},
    {id:"chronic-spontaneous-urticaria",diagnosis:"Acute Urticaria",category:"allergy",acuity:4,setting:"clinic",allergySubtype:"urticaria",allSettings:true,cc:"Daily hives for over 6 weeks, no clear trigger",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"UAS7 severity, step-up: antihistamine to omalizumab, thyroid autoimmunity"},
    {id:"urticarial-vasculitis",diagnosis:"Acute Urticaria",category:"allergy",acuity:3,setting:"consult",allergySubtype:"urticaria",allSettings:true,cc:"Painful hives that last >24hrs and leave bruise-like marks",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Urticarial vasculitis vs CSU, biopsy leukocytoclastic vasculitis, complement, SLE workup"}
  ]},
  { presentation:"Food Allergy", cases:[
    {id:"peanut-allergy-anaphylaxis",diagnosis:"Acute Urticaria",category:"allergy",acuity:1,setting:"ed",allergySubtype:"food-allergy",allSettings:true,cc:"Throat tightness, hives, vomiting after eating peanut at party",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"IgE-mediated peanut anaphylaxis, Ara h 2 component, OIT candidacy, epinephrine Rx"},
    {id:"food-allergy-oit-reaction",diagnosis:"Acute Urticaria",category:"allergy",acuity:3,setting:"clinic",allergySubtype:"food-allergy",allSettings:true,cc:"Hives and stomach pain during oral immunotherapy dose",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"OIT reaction management, dose hold criteria, epinephrine during OIT, cofactor effect"},
    {id:"milk-allergy-infant",diagnosis:"Acute Urticaria",category:"allergy",acuity:3,setting:"consult",allergySubtype:"food-allergy",allSettings:true,cc:"Infant with bloody stools, fussiness, poor feeding on formula",usmle_domain:"PED",usmle_system:"Allergy/Immunology",usmle_topic:"IgE vs non-IgE milk allergy, extensively hydrolyzed vs amino acid formula, OFC timing"}
  ]},
  { presentation:"FPIES", cases:[
    {id:"fpies-acute",diagnosis:"Acute Urticaria",category:"allergy",acuity:2,setting:"ed",allergySubtype:"fpies",allSettings:true,cc:"Infant with profuse vomiting and lethargy 2hrs after feeding",usmle_domain:"PED",usmle_system:"Allergy/Immunology",usmle_topic:"Food protein-induced enterocolitis, profuse vomiting 1-4h, non-IgE mechanism, ondansetron"},
    {id:"fpies-chronic",diagnosis:"Acute Urticaria",category:"allergy",acuity:3,setting:"consult",allergySubtype:"fpies",allSettings:true,cc:"Infant with chronic diarrhea, poor weight gain, irritability with feeds",usmle_domain:"PED",usmle_system:"Allergy/Immunology",usmle_topic:"Chronic FPIES, failure to thrive, food elimination, OFC for diagnosis"}
  ]},
  { presentation:"EoE", cases:[
    {id:"eoe-adult",diagnosis:"Acute Urticaria",category:"allergy",acuity:3,setting:"ed",allergySubtype:"eoe",allSettings:true,cc:"Food stuck in throat, difficulty swallowing solids \u00D7 months",usmle_domain:"IM",usmle_system:"Allergy/Immunology/GI",usmle_topic:"EoE adult presentation, dysphagia, PPI-responsive vs eosinophilic, 6-food elimination"},
    {id:"eoe-pediatric",diagnosis:"Acute Urticaria",category:"allergy",acuity:4,setting:"consult",allergySubtype:"eoe",allSettings:true,cc:"Child with difficulty swallowing, food refusal, chronic heartburn",usmle_domain:"PED",usmle_system:"Allergy/Immunology/GI",usmle_topic:"EoE in children, failure to thrive, food refusal, fluticasone swallowed"}
  ]},
  { presentation:"Atopic Dermatitis", cases:[
    {id:"atopic-dermatitis-severe",diagnosis:"Acute Urticaria",category:"allergy",acuity:4,setting:"clinic",allergySubtype:"eczema",allSettings:true,cc:"Severe itchy rash flare, not sleeping, eczema all over",usmle_domain:"FAM",usmle_system:"Allergy/Immunology",usmle_topic:"Th2 inflammation, dupilumab criteria, topical calcineurin inhibitors, wet wraps"},
    {id:"eczema-herpeticum",diagnosis:"Acute Urticaria",category:"allergy",acuity:2,setting:"ed",allergySubtype:"eczema",allSettings:true,cc:"Painful vesicular rash on face, fever, worsening eczema with punched-out lesions",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Kaposi varicelliform eruption, IV acyclovir, atopic dermatitis complication"}
  ]},
  { presentation:"Allergic Rhinitis", cases:[
    {id:"allergic-rhinitis-uncontrolled",diagnosis:"Acute Urticaria",category:"allergy",acuity:4,setting:"clinic",allergySubtype:"allergic-rhinitis",allSettings:true,cc:"Constant nasal congestion, sneezing, itchy eyes, not controlled with over-the-counter meds",usmle_domain:"FAM",usmle_system:"Allergy/Immunology",usmle_topic:"Intranasal steroids, step-up therapy, allergen testing, immunotherapy candidacy"}
  ]},
  { presentation:"Insect Allergy", cases:[
    {id:"insect-sting-anaphylaxis",diagnosis:"Acute Urticaria",category:"allergy",acuity:1,setting:"ed",allergySubtype:"insect-allergy",allSettings:true,cc:"Bee sting 20min ago, now dizzy, hives, feeling faint",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"VIT indications, tryptase, Api m 1 component testing, epinephrine auto-injector"},
    {id:"venom-immunotherapy-reaction",diagnosis:"Acute Urticaria",category:"allergy",acuity:2,setting:"clinic",allergySubtype:"insect-allergy",allSettings:true,cc:"Hives and wheezing after venom immunotherapy injection",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"VIT systemic reaction, dose hold, pre-medication, long-term VIT duration 5 years"}
  ]},
  { presentation:"Allergic Conjunctivitis", cases:[
    {id:"allergic-conjunctivitis-severe",diagnosis:"Acute Urticaria",category:"allergy",acuity:3,setting:"consult",allergySubtype:"allergic-conjunctivitis",allSettings:true,cc:"Severe bilateral eye itching, tearing, swollen lids, blurred vision",usmle_domain:"FAM",usmle_system:"Allergy/Immunology",usmle_topic:"Vernal vs atopic conjunctivitis, topical antihistamines, steroid risks"}
  ]},
  { presentation:"Drug Allergy", cases:[
    {id:"penicillin-allergy-delabeling",diagnosis:"Acute Urticaria",category:"allergy",acuity:4,setting:"consult",allergySubtype:"drug-allergy",allSettings:true,cc:"Reported penicillin allergy as a child, needs antibiotic for surgery",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"PCN allergy prevalence under 1%, skin testing, graded challenge, de-labeling benefits"},
    {id:"nsaid-hypersensitivity",diagnosis:"Acute Urticaria",category:"allergy",acuity:2,setting:"inpatient",allergySubtype:"drug-allergy",allSettings:true,cc:"Facial swelling and wheezing after taking ibuprofen, nasal polyps",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"NSAID-exacerbated respiratory disease AERD, aspirin desensitization, Samter triad"},
    {id:"drug-allergy-vancomycin-rms",diagnosis:"Acute Urticaria",category:"allergy",acuity:3,setting:"consult",allergySubtype:"drug-allergy",allSettings:true,cc:"Red flushing of face and chest during vancomycin infusion",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Red man syndrome vs true allergy, rate-dependent reaction, skin testing, graded challenge"}
  ]},
  { presentation:"Mast Cell Disease", cases:[
    {id:"mastocytosis",diagnosis:"Acute Urticaria",category:"allergy",acuity:2,setting:"consult",allergySubtype:"mast-cell",allSettings:true,cc:"Flushing episodes, hives with skin stroking, recurrent anaphylaxis",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Serum tryptase, KIT D816V mutation, bone marrow biopsy, trigger avoidance, EpiPen Rx"},
    {id:"mcas-mast-cell",diagnosis:"Mast Cell Activation Syndrome (MCAS)",category:"allergy",acuity:3,cc:"Recurrent multisystem flushing, urticaria, GI cramping and near-syncope — tryptase elevated during attacks",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"MCAS diagnostic criteria, episodic mediator-release symptoms, tryptase elevation, H1+H2 blockers"},
    {id:"alpha-gal-syndrome",diagnosis:"Alpha-Gal Syndrome",category:"allergy",acuity:3,cc:"Delayed urticaria and anaphylaxis 3–4 hours after red meat — recent Lone Star tick bite history",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Lone Star tick, delayed red meat allergy, alpha-gal IgE, tick avoidance"}
  ]},
  { presentation:"Immunodeficiency", cases:[
    {id:"cvid-presentation",diagnosis:"Acute Urticaria",category:"allergy",acuity:4,setting:"clinic",allergySubtype:"immunodeficiency",allSettings:true,cc:"Recurrent sinus and lung infections, 4 courses of antibiotics this year",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"CVID diagnostic criteria, IgG replacement, recurrent sinopulmonary infections, granulomas"},
    {id:"xla-brutons",diagnosis:"X-Linked Agammaglobulinemia (XLA)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"immunodeficiency",allSettings:true,cc:"2-year-old male with 4th serious bacterial infection — septic arthritis, recurrent encapsulated bacteria since 6 months",usmle_domain:"PED",usmle_system:"Allergy/Immunology",usmle_topic:"X-linked agammaglobulinemia, BTK mutation, absent B cells, IgG replacement, prophylactic antibiotics"},
    {id:"scid-ada",diagnosis:"Severe Combined Immunodeficiency (ADA-SCID)",category:"allergy",acuity:1,setting:"ed",allergySubtype:"immunodeficiency",allSettings:true,cc:"6-week-old referred urgently — absent TRECs on newborn screening, no symptoms yet",usmle_domain:"PED",usmle_system:"Allergy/Immunology",usmle_topic:"SCID newborn screening, ADA deficiency, HSCT curative, PEG-ADA bridge, irradiated blood products"},
    {id:"digeorge-22q11",diagnosis:"DiGeorge Syndrome (22q11.2 Deletion)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"immunodeficiency",allSettings:true,cc:"Newborn with truncus arteriosus, hypocalcemia seizure, and cleft palate — 22q11.2 evaluation",usmle_domain:"PED",usmle_system:"Allergy/Immunology",usmle_topic:"DiGeorge syndrome, 22q11 deletion, T-cell deficiency, hypocalcemia, cardiac defects"},
    {id:"cgd-xlinked",diagnosis:"Chronic Granulomatous Disease (X-linked CGD)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"immunodeficiency",allSettings:true,cc:"5-year-old with 3rd suppurative lymphadenitis, prior S. aureus liver abscess and Aspergillus pneumonia",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Chronic granulomatous disease, DHR flow cytometry, TMP-SMX prophylaxis, aspergillus risk"}
  ]},
  { presentation:"Contact Dermatitis", cases:[
    {id:"contact-dermatitis-occupational",diagnosis:"Acute Urticaria",category:"allergy",acuity:4,setting:"clinic",allergySubtype:"contact-dermatitis",allSettings:true,cc:"Itchy, blistering rash on hands, worse at work",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Type IV hypersensitivity, patch testing, allergen avoidance, occupational exposure"}
  ]},
  {presentation:"Allergy Variations",cases:[
    {id:"anaphylaxis-v2",diagnosis:"Anaphylaxis (Elderly + Beta-Blocker)",category:"allergy",acuity:1,setting:"ed",allergySubtype:"anaphylaxis",allSettings:true,variation:true,note:"72M on metoprolol, bee sting, blunted tachycardia, lives alone, Mandarin-speaking",cc:"Bee sting, feeling dizzy and weak, swelling at sting site spreading",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"Epinephrine IM first-line, biphasic reaction, observation period"},
    {id:"anaphylaxis-v3",diagnosis:"Anaphylaxis (Latex, Occupational)",category:"allergy",acuity:1,setting:"ed",allergySubtype:"anaphylaxis",allSettings:true,variation:true,note:"32F uninsured house cleaner, latex exposure, expired EpiPen, Spanish-speaking",cc:"Difficulty breathing, hives on hands and arms after cleaning with gloves",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"Anaphylaxis recognition and management, epinephrine timing"},
    {id:"anaphylaxis-v4",diagnosis:"Anaphylaxis (Adolescent, Psychosocial)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"anaphylaxis",allSettings:true,variation:true,note:"16F peanut, school event, EpiPen embarrassment, food allergy anxiety, social avoidance",cc:"Ate something at school event, throat feels tight, scared to use EpiPen",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"Anaphylaxis in procedural setting, latex trigger, tryptase"},
    {id:"anaphylaxis-v5",diagnosis:"Anaphylaxis (Pediatric, Cultural/Language)",category:"allergy",acuity:1,setting:"ed",allergySubtype:"anaphylaxis",allSettings:true,variation:true,note:"8F sesame, Syrian refugee family, Arabic-only parents, food bank exposure, cultural diet impact",cc:"Child with hives, vomiting, wheezing after eating food from food bank",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"Anaphylaxis differential, cofactor-dependent, NSAID + exercise"},
    {id:"chronic-spontaneous-urticaria-v2",diagnosis:"CSU (Refractory + Autoimmune)",category:"allergy",acuity:3,setting:"ed",allergySubtype:"urticaria",allSettings:true,variation:true,note:"55M construction worker, autoimmune thyroiditis, pressure urticaria, depression, divorce stress",cc:"Daily hives for months, worse with pressure from tool belt, nothing is working",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"UAS7 severity, step-up: antihistamine to omalizumab, thyroid autoimmunity"},
    {id:"penicillin-allergy-delabeling-v2",diagnosis:"PCN Delabeling (Pregnancy + GBS)",category:"allergy",acuity:3,setting:"consult",allergySubtype:"drug-allergy",allSettings:true,variation:true,note:"38F 34wk pregnant, GBS positive, unverified childhood allergy, urgent delabeling for intrapartum prophylaxis",cc:"Pregnant, GBS positive, told I'm allergic to penicillin as a child, need antibiotics for delivery",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"PCN allergy prevalence under 1%, skin testing, graded challenge, de-labeling benefits"},
    {id:"atopic-dermatitis-severe-v2",diagnosis:"Severe AD (Pediatric, SDOH)",category:"allergy",acuity:3,setting:"ed",allergySubtype:"atopic-dermatitis",allSettings:true,variation:true,note:"4M MRSA superinfection, public housing cockroach/mold, single mother, adherence barriers, regimen simplification",cc:"Child's eczema much worse, oozing and crusting, fever, not improving with creams",usmle_domain:"FAM",usmle_system:"Allergy/Immunology",usmle_topic:"Th2 inflammation, dupilumab criteria, topical calcineurin inhibitors, wet wraps"},
    {id:"peanut-allergy-anaphylaxis-v2",diagnosis:"Food Allergy (Misattributed Trigger)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"food-allergy",allSettings:true,variation:true,note:"3M first reaction, assumed peanut but actually CASHEW, importance of component testing",cc:"Toddler with hives and vomiting after eating trail mix for first time",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"IgE-mediated peanut anaphylaxis, Ara h 2 component, OIT candidacy, epinephrine Rx"},
    {id:"eoe-adult-v2",diagnosis:"EoE (Diagnostic Delay)",category:"allergy",acuity:3,setting:"ed",allergySubtype:"eoe",allSettings:true,variation:true,note:"29M 3-year GERD misdiagnosis, adaptive eating behaviors, social impact, food impaction",cc:"Food stuck in chest, can't swallow, been having trouble eating solids for years",usmle_domain:"IM",usmle_system:"Allergy/Immunology/GI",usmle_topic:"EoE adult presentation, dysphagia, PPI-responsive vs eosinophilic, 6-food elimination"}
  ]},
  {presentation:"Allergy Variations — Batch 2-3",cases:[
    {id:"ace-angioedema-v2",diagnosis:"ACE Angioedema (AA Female, CHF, Late-Onset)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"angioedema",allSettings:true,variation:true,cc:"Tongue and lip swelling, been on blood pressure medication for years",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"ACE inhibitor angioedema, bradykinin mechanism, switch to ARB"},
    {id:"acquired-c1esterase-inhibitor-deficiency-v2",diagnosis:"Acquired C1-INH Deficiency (MGUS-Driven)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"angioedema",allSettings:true,variation:true,cc:"Recurrent facial swelling episodes, antihistamines not helping",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Acquired angioedema, C1-INH deficiency, lymphoproliferative workup"},
    {id:"acute-urticaria-v2",diagnosis:"Acute Urticaria (Post-Viral, Unnecessary Testing)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"urticaria",allSettings:true,variation:true,cc:"Hives started after a cold, now all over body × 5 days",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Acute urticaria triggers, antihistamines, when to use epinephrine"},
    {id:"allergic-angioedema-v2",diagnosis:"Allergic Angioedema (Obesity, Epi Dosing)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"angioedema",allSettings:true,variation:true,cc:"Lip and face swelling, used EpiPen but symptoms not fully resolving",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"IgE-mediated angioedema, epinephrine, airway management"},
    {id:"allergic-conjunctivitis-severe-v2",diagnosis:"Vernal Keratoconjunctivitis (Shield Ulcer)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"conjunctivitis",allSettings:true,variation:true,cc:"Severe eye pain, tearing, photophobia, thick stringy discharge from both eyes",usmle_domain:"FAM",usmle_system:"Allergy/Immunology",usmle_topic:"Vernal vs atopic conjunctivitis, topical antihistamines, steroid risks"},
    {id:"allergic-rhinitis-uncontrolled-v2",diagnosis:"Allergic Rhinitis (Vet Tech, Occupational SCIT)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"rhinitis",allSettings:true,variation:true,cc:"Constant runny nose, sneezing, congestion worse at work with animals",usmle_domain:"FAM",usmle_system:"Allergy/Immunology",usmle_topic:"Intranasal steroids, step-up therapy, allergen testing, immunotherapy candidacy"},
    {id:"contact-dermatitis-occupational-v2",diagnosis:"ACD (Hairstylist, PPD, Career Threat)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"contact-dermatitis",allSettings:true,variation:true,cc:"Blistering rash on hands from hair dye, can't work",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Type IV hypersensitivity, patch testing, allergen avoidance, occupational exposure"},
    {id:"cvid-presentation-v2",diagnosis:"CVID (Insurance Crisis, Diagnostic Delay)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"immunodeficiency",allSettings:true,variation:true,cc:"Recurrent pneumonia, chronic sinusitis, lost insurance and missed infusions",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"CVID diagnostic criteria, IgG replacement, recurrent sinopulmonary infections, granulomas"},
    {id:"dress-syndrome-v2",diagnosis:"DRESS (Allopurinol, HLA-B*58:01, Korean)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"drug-reactions",allSettings:true,variation:true,cc:"Fever, widespread rash, facial swelling 4 weeks after starting gout medication",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"DRESS/DiHS, RegiSCAR score, offending drug withdrawal, systemic steroids"},
    {id:"drug-allergy-vancomycin-rms-v2",diagnosis:"Vancomycin RMS (Elderly, False Allergy Cascade)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"drug-allergy",allSettings:true,variation:true,cc:"Red flushing of neck and chest during antibiotic infusion, itching",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Red man syndrome vs true allergy, rate-dependent reaction, skin testing, graded challenge"},
    {id:"eczema-herpeticum-v2",diagnosis:"Eczema Herpeticum (Toddler, Cold Sore Exposure)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"atopic-dermatitis",allSettings:true,variation:true,cc:"Toddler with worsening eczema, painful blisters on face after grandparent visit",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Kaposi varicelliform eruption, IV acyclovir, atopic dermatitis complication"},
    {id:"eoe-pediatric-v2",diagnosis:"EoE Pediatric (Picky Eater Misdiagnosis, 6yr Delay)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"eoe",allSettings:true,variation:true,cc:"Child with food refusal, gagging, only eats soft foods, called a picky eater",usmle_domain:"PED",usmle_system:"Allergy/Immunology/GI",usmle_topic:"EoE in children, failure to thrive, food refusal, fluticasone swallowed"},
    {id:"erythema-multiforme-major-v2",diagnosis:"EM Major (Recurrent HSV-Triggered)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"drug-reactions",allSettings:true,variation:true,cc:"Target-shaped rash on hands and face, mouth sores, had cold sore last week",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"EM major vs SJS, target lesions, HSV trigger, acyclovir suppression"},
    {id:"food-allergy-oit-reaction-v2",diagnosis:"OIT Reaction (Swimmer, Exercise Window)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"food-allergy",allSettings:true,variation:true,cc:"Hives and throat tightness after swimming, took OIT dose before practice",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"OIT reaction management, dose hold criteria, epinephrine during OIT, cofactor effect"},
    {id:"fpies-acute-v2",diagnosis:"FPIES Acute (School Exposure, EpiPen Failure)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"fpies",allSettings:true,variation:true,cc:"Child vomiting profusely and pale after eating at school, EpiPen given with no improvement",usmle_domain:"PED",usmle_system:"Allergy/Immunology",usmle_topic:"Food protein-induced enterocolitis, profuse vomiting 1-4h, non-IgE mechanism, ondansetron"},
    {id:"fpies-chronic-v2",diagnosis:"FPIES Chronic (Infant FTT, Reflux Misdiagnosis)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"fpies",allSettings:true,variation:true,cc:"Infant with chronic vomiting, not gaining weight, treated for reflux with no improvement",usmle_domain:"PED",usmle_system:"Allergy/Immunology",usmle_topic:"Chronic FPIES, failure to thrive, food elimination, OFC for diagnosis"},
    {id:"hereditary-angioedema-v2",diagnosis:"HAE (College Student, OCP Trigger, Diagnostic Odyssey)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"angioedema",allSettings:true,variation:true,cc:"Recurrent abdominal pain and facial swelling, started after going on birth control",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"C1 esterase inhibitor deficiency, icatibant/C1-INH concentrate, AVOID ACE inhibitors"},
    {id:"idiopathic-angioedema-v2",diagnosis:"Idiopathic Angioedema (Travel Anxiety, Omalizumab)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"angioedema",allSettings:true,variation:true,cc:"Lip and eyelid swelling episodes, afraid to travel, no clear trigger",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Idiopathic histaminergic angioedema, antihistamine trial, rule out HAE, complement levels"},
    {id:"insect-sting-anaphylaxis-v2",diagnosis:"Venom Anaphylaxis (Uninsured Landscape Worker)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"insect-allergy",allSettings:true,variation:true,cc:"Wasp sting while working, hives spreading, feeling dizzy, no insurance",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"VIT indications, tryptase, Api m 1 component testing, epinephrine auto-injector"},
    {id:"mastocytosis-v2",diagnosis:"MCAS (3yr Diagnostic Odyssey, Told Anxiety)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"mast-cell",allSettings:true,variation:true,cc:"Flushing, racing heart, abdominal pain, told it's anxiety for 3 years",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Serum tryptase, KIT D816V mutation, bone marrow biopsy, trigger avoidance"},
    {id:"milk-allergy-infant-v2",diagnosis:"CMPA (Breastfed, Mother Misconception)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"food-allergy",allSettings:true,variation:true,cc:"Breastfed infant with bloody stools, eczema, fussy after feeds",usmle_domain:"PED",usmle_system:"Allergy/Immunology",usmle_topic:"IgE vs non-IgE milk allergy, extensively hydrolyzed vs amino acid formula, OFC timing"},
    {id:"nsaid-hypersensitivity-v2",diagnosis:"AERD/Samter Triad (Chef with Anosmia)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"drug-allergy",allSettings:true,variation:true,cc:"Asthma attack after taking aspirin, nasal polyps, can't smell anymore",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"NSAID-exacerbated respiratory disease AERD, aspirin desensitization, Samter triad"},
    {id:"severe-allergic-reaction-v2",diagnosis:"Contrast Reaction (Premedication Failure)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"anaphylaxis",allSettings:true,variation:true,cc:"Hives, throat tightness after CT contrast despite taking premedication",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"Grading anaphylaxis severity, epinephrine dosing, adjuncts after epinephrine"},
    {id:"severe-allergic-reaction-v3",diagnosis:"Amoxicillin Delabeling (College Athlete)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"drug-allergy",allSettings:true,variation:true,cc:"Rash as a child with amoxicillin, now needs antibiotic before dental work",usmle_domain:"EM",usmle_system:"Allergy/Immunology",usmle_topic:"Grading anaphylaxis severity, epinephrine dosing, adjuncts after epinephrine"},
    {id:"sjs-ten-v2",diagnosis:"SJS/TEN (Lamotrigine, HLA-B*15:13)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"drug-reactions",allSettings:true,variation:true,cc:"Painful skin peeling, blisters, high fever 2 weeks after starting seizure medication",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"SCORTEN score, offending drug withdrawal, wound care, cyclosporine vs IVIG vs TNF-alpha inhibitors"},
    {id:"sjsten-overlap-v2",diagnosis:"SJS/TEN Overlap (HIV + Bactrim)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"drug-reactions",allSettings:true,variation:true,cc:"Widespread skin sloughing, mouth sores, high fever after starting antibiotic",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"SJS-TEN overlap 10-30% BSA, SCORTEN, ICU burn-unit care"},
    {id:"urticarial-vasculitis-v2",diagnosis:"Urticarial Vasculitis (Hypocomplementemic)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"urticaria",allSettings:true,variation:true,cc:"Painful hives that burn rather than itch, leaving dark marks, joint pain",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Urticarial vasculitis vs CSU, biopsy leukocytoclastic vasculitis, complement, SLE workup"},
    {id:"venom-immunotherapy-reaction-v2",diagnosis:"VIT Reaction (ACE Inhibitor Amplification)",category:"allergy",acuity:2,setting:"ed",allergySubtype:"insect-allergy",allSettings:true,variation:true,cc:"Lightheaded, flushing, wheezing after allergy shot, on blood pressure medication",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"VIT systemic reaction, dose hold, pre-medication, long-term VIT duration 5 years"}
  ]},
  { presentation:"Trauma", cases:[
    {id:"tension-ptx",diagnosis:"Tension Pneumothorax",category:"trauma",acuity:1,cc:"Chest trauma, severe difficulty breathing, neck veins distended",usmle_domain:"EM",usmle_system:"Pulmonary",usmle_topic:"Tracheal deviation, absent breath sounds, JVD, needle decompression 2nd ICS MCL, chest tube"},
    {id:"epidural-hematoma",diagnosis:"Epidural Hematoma",category:"trauma",acuity:1,cc:"Head injury, brief LOC then lucid, now rapidly declining",usmle_domain:"SUR",usmle_system:"Neurology/Neurosurgery",usmle_topic:"Lucid interval, lens-shaped bleed, middle meningeal artery, emergent craniotomy"}
  ]},
  { presentation:"Vascular Emergency", cases:[
    {id:"aaa-v1",diagnosis:"Ruptured Abdominal Aortic Aneurysm",category:"vascular",acuity:1,cc:"Sudden severe abdominal and back pain, feeling faint",usmle_domain:"IM",usmle_system:"Allergy/Immunology",usmle_topic:"Alpha-1 antitrypsin deficiency, ZZ phenotype, emphysema + liver disease"},
    {id:"acute-limb-ischemia",diagnosis:"Acute Limb Ischemia",category:"vascular",acuity:2,cc:"Sudden painful cold left leg, can't feel foot",usmle_domain:"SUR",usmle_system:"Vascular Surgery",usmle_topic:"6 Ps, Rutherford classification, embolectomy vs anticoagulation"}
  ]},
  { presentation:"GI Emergency", cases:[
    {id:"gi-bleed-syncope",diagnosis:"Upper GI Hemorrhage with Syncope",category:"gi",acuity:2,cc:"Vomiting blood, black stools, passed out at home",usmle_domain:"IM",usmle_system:"GI",usmle_topic:"GI bleed presenting as syncope, hemodynamic instability, resuscitation before endoscopy"},
    {id:"severe-pancreatitis",diagnosis:"Acute Necrotizing Pancreatitis",category:"gi",acuity:2,cc:"Severe epigastric pain radiating to back, vomiting, fever",usmle_domain:"IM",usmle_system:"GI",usmle_topic:"BISAP score, necrotizing pancreatitis, IVF with LR, early enteral nutrition, ERCP indications"}
  ]},
  { presentation:"Obstetric Emergency", cases:[
    {id:"ectopic-pregnancy",diagnosis:"Ruptured Ectopic Pregnancy",category:"obstetric",acuity:1,cc:"Sudden severe lower abdominal pain, vaginal spotting, dizzy",usmle_domain:"OB",usmle_system:"OB/GYN",usmle_topic:"Discriminatory zone, serial beta-hCG, MTX vs surgical, unstable = OR"},
    {id:"ectopic-pregnancy-workup",diagnosis:"Ruptured Ectopic Pregnancy — Hemorrhagic Shock — Emergency Salpingectomy",category:"obstetric",acuity:1,cc:"30F G1P0 6wk LMP + positive UPT — left adnexal mass + hemoperitoneum — BP 88/54 — OR now",usmle_domain:"OB",usmle_system:"OB/GYN",usmle_topic:"Discriminatory zone, empty uterus positive UPT, MTX contraindications"},
    {id:"eclampsia",diagnosis:"Eclampsia",category:"obstetric",acuity:1,cc:"Pregnant, severe headache, seizure, high blood pressure",usmle_domain:"OB",usmle_system:"OB/GYN",usmle_topic:"Mg sulfate for seizures, BP targets, emergent delivery, postpartum eclampsia risk"}
  ]},
  { presentation:"Pediatric Emergency", cases:[
    {id:"epiglottitis",diagnosis:"Acute Epiglottitis",category:"pediatric",acuity:1,cc:"Child with sore throat, drooling, difficulty swallowing, stridor",usmle_domain:"EM",usmle_system:"Pediatrics/ENT",usmle_topic:"Thumbprint sign, secure airway first, Hib vaccine prevention, adult epiglottitis"},
    {id:"intussusception",diagnosis:"Ileocolic Intussusception",category:"pediatric",acuity:2,cc:"Infant with intermittent crying episodes, currant jelly stools, vomiting",usmle_domain:"PED",usmle_system:"Pediatrics/GI",usmle_topic:"Target sign on US, air contrast enema reduction, surgical criteria if failed reduction"},
    {id:"croup-epiglottitis-ddx",diagnosis:"Moderate Croup — Westley Score 5 — vs Epiglottitis Differential",category:"pediatric",acuity:2,cc:"3yo barky cough + inspiratory stridor — dexamethasone + racemic epinephrine — observe 4h",usmle_domain:"PED",usmle_system:"Pediatrics/ENT",usmle_topic:"Westley score, steeple vs thumbprint sign, single-dose dexamethasone, Hib vaccine"}
  ]},
  { presentation:"Eye Emergency", cases:[
    {id:"angle-closure-glaucoma",diagnosis:"Acute Angle-Closure Glaucoma",category:"ophthalmology",acuity:2,cc:"Sudden severe eye pain, blurred vision, halos around lights, nausea",usmle_domain:"EM",usmle_system:"Ophthalmology",usmle_topic:"Pilocarpine, timolol, acetazolamide, urgent ophthalmology referral"},
    {id:"crao",diagnosis:"Central Retinal Artery Occlusion",category:"ophthalmology",acuity:2,cc:"Sudden painless vision loss in one eye, like a curtain coming down",usmle_domain:"EM",usmle_system:"Ophthalmology",usmle_topic:"Central retinal artery occlusion, IOP reduction, ocular massage, stroke workup urgency"}
  ]},
  { presentation:"Urologic Emergency", cases:[
    {id:"testicular-torsion",diagnosis:"Testicular Torsion",category:"urology",acuity:2,cc:"Sudden severe testicular pain, nausea, swelling",usmle_domain:"SUR",usmle_system:"Urology",usmle_topic:"6h salvage window, manual detorsion open book, surgical exploration, false negative US"}
  ]},
  { presentation:"ENT / Airway Emergency", cases:[
    {id:"peritonsillar-abscess",diagnosis:"Peritonsillar Abscess",category:"ent",acuity:3,cc:"Severe sore throat, can't swallow, muffled voice, trismus",usmle_domain:"EM",usmle_system:"ENT",usmle_topic:"Uvular deviation, hot potato voice, needle aspiration vs I and D, ampicillin-sulbactam"},
    {id:"ludwigs-angina",diagnosis:"Ludwig Angina",category:"ent",acuity:1,cc:"Floor of mouth swelling, difficulty swallowing and breathing, recent dental pain",usmle_domain:"EM",usmle_system:"ENT/Surgery",usmle_topic:"Floor-of-mouth cellulitis, airway threat, awake fiberoptic intubation, IV penicillin + metronidazole"}
  ]},
  { presentation:"Geriatric Emergency", cases:[
    {id:"hip-fracture-anticoag",diagnosis:"Hip Fracture on Anticoagulation",category:"geriatric",acuity:3,cc:"Fall, unable to bear weight, on blood thinner",usmle_domain:"SUR",usmle_system:"Musculoskeletal/Surgery",usmle_topic:"Operative timing, VTE prophylaxis, DOAC bridging, orthogeriatrics co-management"},
    {id:"subdural-hematoma",diagnosis:"Acute-on-Chronic Subdural Hematoma",category:"geriatric",acuity:2,cc:"Elderly, progressive confusion, headache, history of falls, on anticoagulation",usmle_domain:"SUR",usmle_system:"Neurology/Neurosurgery",usmle_topic:"Acute vs chronic SDH, crescent-shaped, elderly fall, craniotomy vs burr hole, anticoag reversal"}
  ]},
  { presentation:"Environmental Emergency", cases:[
    {id:"heat-stroke",diagnosis:"Exertional Heat Stroke",category:"environmental",acuity:1,cc:"Collapsed during exercise in heat, very hot, confused, not sweating",usmle_domain:"EM",usmle_system:"Environmental Medicine",usmle_topic:"Classic vs exertional heat stroke, core temp above 40C, evaporative cooling, rhabdo risk"},
    {id:"severe-hypothermia",diagnosis:"Severe Accidental Hypothermia",category:"environmental",acuity:1,cc:"Found outdoors in cold, unresponsive, very low body temperature",usmle_domain:"EM",usmle_system:"Environmental Medicine",usmle_topic:"Afterdrop, ECMO rewarming in cardiac arrest, active internal rewarming, temperature monitoring"}
  ]}
];
var CASE_MANIFEST = window.CASE_MANIFEST || {};
CASE_MANIFEST.cases = [];
EMR_MANIFEST.forEach(function(g){g.cases.forEach(function(c){CASE_MANIFEST.cases.push(c)})});
CASE_MANIFEST.batches = EMR_MANIFEST;
CASE_MANIFEST.version = '2.0.0';
CASE_MANIFEST.totalCases = CASE_MANIFEST.cases.length;
